// Better-Auth-generated auth tables (user/session/account/verification) + the Phase-1
// capability (canBook/canHost/role) and profile (firstName.. avatarPublicId) additionalFields
// declared in src/lib/auth.ts. Regenerate with `npx @better-auth/cli generate` after any
// change to auth.ts additionalFields — do NOT hand-edit the AUTH table SHAPE here (RESEARCH Pitfall 1).
//
// HAND-AUTHORED Phase-2 tables (NOT regenerated by the Better Auth CLI — Better Auth owns ONLY
// user/session/account/verification): listing, listing_photo, listing_amenity, listing_activity_tag,
// and host_payout. These are the marketplace supply-side model (FK-rooted at user.id) and must be
// preserved on any auth-schema regen. Money is integer minor units (cents), never float (Pitfall 5);
// geo is a PostGIS geometry(point,4326) column with x=lng / y=lat (Pitfall 1).
//
// Manual post-generation tweak (kept on regen): all timestamp columns are timezone-aware
// (`timestamptz`, withTimezone:true) to honor the project's UTC-everywhere constraint
// (CLAUDE.md "What NOT to Use" — never store naive timestamps).

import { relations, sql } from "drizzle-orm";
import {
  pgTable,
  pgEnum,
  text,
  integer,
  timestamp,
  time,
  boolean,
  index,
  uniqueIndex,
  geometry,
} from "drizzle-orm/pg-core";

export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").default(false).notNull(),
  image: text("image"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .defaultNow()
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
  canBook: boolean("can_book").default(false).notNull(),
  canHost: boolean("can_host").default(false).notNull(),
  role: text("role").default("user"),
  firstName: text("first_name").notNull(),
  lastName: text("last_name"),
  phone: text("phone"),
  bio: text("bio"),
  city: text("city"),
  avatarUrl: text("avatar_url"),
  avatarPublicId: text("avatar_public_id"),
});

export const session = pgTable(
  "session",
  {
    id: text("id").primaryKey(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    token: text("token").notNull().unique(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
  },
  (table) => [index("session_userId_idx").on(table.userId)],
);

export const account = pgTable(
  "account",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at", { withTimezone: true }),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at", { withTimezone: true }),
    scope: text("scope"),
    password: text("password"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  (table) => [index("account_userId_idx").on(table.userId)],
);

export const verification = pgTable(
  "verification",
  {
    id: text("id").primaryKey(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .defaultNow()
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  (table) => [index("verification_identifier_idx").on(table.identifier)],
);

export const userRelations = relations(user, ({ many }) => ({
  sessions: many(session),
  accounts: many(account),
}));

export const sessionRelations = relations(session, ({ one }) => ({
  user: one(user, {
    fields: [session.userId],
    references: [user.id],
  }),
}));

export const accountRelations = relations(account, ({ one }) => ({
  user: one(user, {
    fields: [account.userId],
    references: [user.id],
  }),
}));

// ---------------------------------------------------------------------------
// Phase-2 listing model (HAND-AUTHORED — see file header). FK-rooted at user.id.
// ---------------------------------------------------------------------------

// Fixed curated enums (D-05/D-08). Declared before the tables that reference them (const TDZ).
export const listingStatus = pgEnum("listing_status", ["draft", "published", "unlisted"]);
export const bookingMode = pgEnum("booking_mode", ["instant", "request"]);
export const spaceType = pgEnum("space_type", [
  "pickleball_court",
  "tennis_court",
  "basketball_court",
  "multi_sport_court",
  "gym_fitness_floor",
  "yoga_studio",
  "dance_studio",
  "pilates_barre_studio",
  "martial_arts_boxing",
  "home_private_gym",
  "multi_purpose_event",
]);

export const listing = pgTable(
  "listing",
  {
    id: text("id").primaryKey(), // app-generated uuid (matches user.id text PK)
    hostId: text("host_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    title: text("title"), // nullable in draft; required at publish (publishSchema)
    description: text("description"),
    primarySpaceType: spaceType("primary_space_type"), // D-05/D-08 canonical primary type
    // Structured address (D-10) — nullable in draft, required at publish.
    addressLine1: text("address_line1"),
    addressLine2: text("address_line2"),
    city: text("city"),
    region: text("region"),
    postalCode: text("postal_code"),
    country: text("country"),
    neighborhood: text("neighborhood"), // approximate-display anchor (D-09)
    // PostGIS point (D-10). AXIS ORDER: x = longitude, y = latitude. Humans say "lat,lng" but
    // PostGIS stores (x=lng, y=lat) — always persist with { x: lng, y: lat } (RESEARCH Pitfall 1).
    location: geometry("location", { type: "point", mode: "xy", srid: 4326 }),
    showExactAddress: boolean("show_exact_address").default(false).notNull(), // D-09 default approximate
    maxOccupancy: integer("max_occupancy"), // D-07 single capacity int
    unitCount: integer("unit_count").default(1).notNull(), // D-21 (1 = exclusive whole-space; N = multi-unit venue)
    timezone: text("timezone").default("Asia/Manila").notNull(), // D-27 (IANA; default launch region — drives calendar display)
    hourlyRateCents: integer("hourly_rate_cents"), // D-03 integer minor units (Pitfall 5)
    dayRateCents: integer("day_rate_cents"), // D-03
    currency: text("currency").default("usd").notNull(), // single-region; column future-proofs
    bookingMode: bookingMode("booking_mode").default("request").notNull(), // D-04 stored, wired Phase 6
    status: listingStatus("status").default("draft").notNull(), // D-02/LIST-05
    publishedAt: timestamp("published_at", { withTimezone: true }),
    deletedAt: timestamp("deleted_at", { withTimezone: true }), // soft-delete (Claude's discretion)
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .defaultNow()
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  (t) => [
    index("listing_host_idx").on(t.hostId),
    index("listing_status_idx").on(t.status),
    index("listing_location_gist").using("gist", t.location), // Phase-4 radius search ready
  ],
);

export const listingPhoto = pgTable(
  "listing_photo",
  {
    id: text("id").primaryKey(),
    listingId: text("listing_id")
      .notNull()
      .references(() => listing.id, { onDelete: "cascade" }),
    publicId: text("public_id").notNull(), // Cloudinary public_id — needed for destroy (orphan cleanup)
    url: text("url").notNull(), // secure_url
    position: integer("position").notNull(), // 0 = cover (D-04)
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    index("listing_photo_listing_idx").on(t.listingId),
    uniqueIndex("listing_photo_position_uq").on(t.listingId, t.position), // stable ordering invariant
  ],
);

// Amenities & activity tags as JOIN tables (NOT array columns) — keeps Phase-4 filters
// indexable & clean (D-05/D-06).
export const listingAmenity = pgTable(
  "listing_amenity",
  {
    listingId: text("listing_id")
      .notNull()
      .references(() => listing.id, { onDelete: "cascade" }),
    amenity: text("amenity").notNull(),
  },
  (t) => [uniqueIndex("listing_amenity_uq").on(t.listingId, t.amenity)],
);

export const listingActivityTag = pgTable(
  "listing_activity_tag",
  {
    listingId: text("listing_id")
      .notNull()
      .references(() => listing.id, { onDelete: "cascade" }),
    tag: text("tag").notNull(),
  },
  (t) => [uniqueIndex("listing_activity_tag_uq").on(t.listingId, t.tag)],
);

// Host payout state — a SEPARATE table keyed 1:1 to user (NOT Better Auth additionalFields, to keep
// the auth schema CLI-clean). PayMongo shape (D-20): activation is set ONLY by the Plan-06
// merchant.activated webhook; payoutsEnabled is the provider-agnostic cached gate flag deriveBookable
// reads (KEEP THIS NAME). These flags are webhook/server-set ONLY — never from a client body.
export const hostPayout = pgTable("host_payout", {
  userId: text("user_id")
    .primaryKey()
    .references(() => user.id, { onDelete: "cascade" }),
  paymongoAccountId: text("paymongo_account_id").unique(), // host's PayMongo Linked-Account id
  activationStatus: text("activation_status").default("pending").notNull(), // pending|activated|declined
  payoutsEnabled: boolean("payouts_enabled").default(false).notNull(), // cached gate flag (deriveBookable)
  onboardingComplete: boolean("onboarding_complete").default(false).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .defaultNow()
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
});

// PayMongo webhook idempotency ledger (PAY-04 / T-06-REPLAY). One row per PROCESSED event id; the
// webhook route checks this BEFORE applying an event so a double-delivered / retried PayMongo webhook
// is a no-op (duplicate → 200 skip). Hand-authored (not a Better Auth table); preserve on any auth regen.
export const paymongoEvent = pgTable("paymongo_event", {
  id: text("id").primaryKey(), // the PayMongo event id (data.id) — the idempotency key
  type: text("type").notNull(), // e.g. merchant.activated / merchant.declined
  processedAt: timestamp("processed_at", { withTimezone: true }).defaultNow().notNull(),
});

// ---------------------------------------------------------------------------
// Phase-3 availability model (HAND-AUTHORED — the double-booking keystone, D-21/D-28).
// operating_hours (recurring weekly windows), availability_block (close-only overrides), and
// booking (the occupancy table). The GiST EXCLUDE that makes overlaps structurally impossible
// lives in drizzle/0005_booking_exclusion.sql — Drizzle CANNOT express EXCLUDE (see `booking`).
// ---------------------------------------------------------------------------

// Booking-status enum. Declared before `booking` (const TDZ), mirroring listingStatus (line 135).
// Declared forward-compatibly — Phase 4 owns the full state machine. Phase 3 references ONLY
// 'pending'/'confirmed' (the 0005 partial WHERE occupying set); the rest are inert until Phase 4.
export const bookingStatus = pgEnum("booking_status", [
  "pending",
  "confirmed",
  "cancelled",
  "declined",
  "completed",
]);

// Recurring weekly operating hours (AVAIL-01, D-25). Multiple windows/day = multiple rows with the
// same (listingId, dayOfWeek). Hours are listing-wide (all units share). Times are venue-local wall
// clock (Postgres `time`, no tz) — combine with a concrete venue-local date via TZDate for a UTC instant.
export const operatingHours = pgTable(
  "operating_hours",
  {
    id: text("id").primaryKey(),
    listingId: text("listing_id")
      .notNull()
      .references(() => listing.id, { onDelete: "cascade" }),
    dayOfWeek: integer("day_of_week").notNull(), // 0=Sun..6=Sat (JS Date.getDay convention, A1)
    openTime: time("open_time").notNull(), // venue-local wall clock
    closeTime: time("close_time").notNull(), // must be > openTime (server-validated; no midnight cross v1)
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [index("operating_hours_listing_idx").on(t.listingId)],
);

// Close-only availability overrides (AVAIL-02, D-24). unit NULL = whole listing blocked; else one
// unit. A block is subtractive in the read model; "unblock" = delete the row. Block-vs-booking is NOT
// DB-enforced here (Open Question Q1 RESOLVED) — the Phase-4 server action guards it in-transaction.
export const availabilityBlock = pgTable(
  "availability_block",
  {
    id: text("id").primaryKey(),
    listingId: text("listing_id")
      .notNull()
      .references(() => listing.id, { onDelete: "cascade" }),
    unit: integer("unit"), // NULL = whole listing; else one unit (D-24)
    startsAt: timestamp("starts_at", { withTimezone: true }).notNull(),
    endsAt: timestamp("ends_at", { withTimezone: true }).notNull(),
    reason: text("reason"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [index("availability_block_listing_idx").on(t.listingId)],
);

// The occupancy table + the double-booking keystone (D-21/D-28, SC#4). Each booking reserves exactly
// ONE unit (bare index 1..unitCount) for its [startsAt, endsAt) window.
//
// EXCLUDE "booking_no_overlap" is HAND-AUTHORED in drizzle/0005_booking_exclusion.sql — Drizzle
// cannot express EXCLUDE (issues #2813/#3388). `drizzle-kit generate` will NOT produce it; never
// assume the constraint exists from THIS file alone. See 0005_booking_exclusion.sql for the
// `EXCLUDE USING gist (listing_id =, unit =, tstzrange('[)') &&) WHERE status IN ('pending','confirmed')`.
//
// Phase-4 adds the pending-hold lifecycle columns (expiresAt/quotedTotalCents/currency/idempotencyKey)
// + the booking_idem_uq partial-unique index. Unlike EXCLUDE, these ARE Drizzle-expressible and go
// through `drizzle-kit generate` (drizzle/0006_booking_hold.sql) — only the EXCLUDE stays hand-authored.
export const booking = pgTable(
  "booking",
  {
    id: text("id").primaryKey(),
    listingId: text("listing_id")
      .notNull()
      .references(() => listing.id, { onDelete: "cascade" }),
    unit: integer("unit").notNull(), // bare index 1..unitCount (D-21)
    bookerId: text("booker_id")
      .notNull()
      .references(() => user.id, { onDelete: "restrict" }), // A5 — bookings are financial records; never cascade-delete
    startsAt: timestamp("starts_at", { withTimezone: true }).notNull(),
    endsAt: timestamp("ends_at", { withTimezone: true }).notNull(),
    status: bookingStatus("status").default("confirmed").notNull(),
    // Pending-hold lifecycle (D-49, Phase 4). All new columns are nullable-safe — there are no existing
    // booking rows in dev/UAT (A7) — so 0006 is a backfill-free ADD COLUMN.
    expiresAt: timestamp("expires_at", { withTimezone: true }), // hold TTL; only meaningful while 'pending' (NULL once confirmed/terminal). D-48 lazy expiry treats a past value as FREE.
    quotedTotalCents: integer("quoted_total_cents"), // price frozen at hold time (Phase-5 charge integrity, D-49)
    currency: text("currency").default("php").notNull(), // freeze the display/charge currency (D-46)
    idempotencyKey: text("idempotency_key"), // nullable client token — double-click backstop (D-42)
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    index("booking_listing_idx").on(t.listingId),
    // Partial-unique idempotency index (D-42 / RESEARCH Pattern 6): at most one booking per client token.
    // Drizzle CAN express a partial unique index via .where() (same idiom as listing_photo_position_uq);
    // scoping to non-NULL keys lets the many holds placed without a token coexist.
    uniqueIndex("booking_idem_uq").on(t.idempotencyKey).where(sql`idempotency_key IS NOT NULL`),
  ],
);

export const listingRelations = relations(listing, ({ one, many }) => ({
  host: one(user, {
    fields: [listing.hostId],
    references: [user.id],
  }),
  photos: many(listingPhoto),
  amenities: many(listingAmenity),
  activityTags: many(listingActivityTag),
  operatingHours: many(operatingHours),
  blocks: many(availabilityBlock),
  bookings: many(booking),
}));

export const operatingHoursRelations = relations(operatingHours, ({ one }) => ({
  listing: one(listing, {
    fields: [operatingHours.listingId],
    references: [listing.id],
  }),
}));

export const availabilityBlockRelations = relations(availabilityBlock, ({ one }) => ({
  listing: one(listing, {
    fields: [availabilityBlock.listingId],
    references: [listing.id],
  }),
}));

export const bookingRelations = relations(booking, ({ one }) => ({
  listing: one(listing, {
    fields: [booking.listingId],
    references: [listing.id],
  }),
  booker: one(user, {
    fields: [booking.bookerId],
    references: [user.id],
  }),
}));
