// Better-Auth-generated auth tables (user/session/account/verification) + the Phase-1
// capability (canBook/canHost/role) and profile (firstName.. avatarPublicId) additionalFields
// declared in src/lib/auth.ts. Regenerate with `npx @better-auth/cli generate` after any
// change to auth.ts additionalFields — do NOT hand-edit the AUTH table SHAPE here (RESEARCH Pitfall 1).
//
// HAND-AUTHORED Phase-2 tables (NOT regenerated by the Better Auth CLI — Better Auth owns ONLY
// user/session/account/verification): listing, listing_photo, listing_amenity, listing_activity_tag,
// and host_payout. These are the marketplace supply-side model (FK-rooted at user.id) and must be
// preserved on any auth-schema regen. Money is integer minor units (cents), never float (Pitfall 5);
// geo is a PostGIS geometry(point,4326) column with x=lng / y=lat (Pitfall 1).
//
// Manual post-generation tweak (kept on regen): all timestamp columns are timezone-aware
// (`timestamptz`, withTimezone:true) to honor the project's UTC-everywhere constraint
// (CLAUDE.md "What NOT to Use" — never store naive timestamps).

import { relations, sql } from "drizzle-orm";
import {
  pgTable,
  pgEnum,
  text,
  integer,
  timestamp,
  time,
  boolean,
  index,
  uniqueIndex,
  unique,
  jsonb,
  geometry,
} from "drizzle-orm/pg-core";

export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").default(false).notNull(),
  image: text("image"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .defaultNow()
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
  canBook: boolean("can_book").default(false).notNull(),
  canHost: boolean("can_host").default(false).notNull(),
  role: text("role").default("user"),
  firstName: text("first_name").notNull(),
  lastName: text("last_name"),
  phone: text("phone"),
  bio: text("bio"),
  city: text("city"),
  avatarUrl: text("avatar_url"),
  avatarPublicId: text("avatar_public_id"),
});

export const session = pgTable(
  "session",
  {
    id: text("id").primaryKey(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    token: text("token").notNull().unique(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
  },
  (table) => [index("session_userId_idx").on(table.userId)],
);

export const account = pgTable(
  "account",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at", { withTimezone: true }),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at", { withTimezone: true }),
    scope: text("scope"),
    password: text("password"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  (table) => [index("account_userId_idx").on(table.userId)],
);

export const verification = pgTable(
  "verification",
  {
    id: text("id").primaryKey(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .defaultNow()
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  (table) => [index("verification_identifier_idx").on(table.identifier)],
);

export const userRelations = relations(user, ({ many }) => ({
  sessions: many(session),
  accounts: many(account),
}));

export const sessionRelations = relations(session, ({ one }) => ({
  user: one(user, {
    fields: [session.userId],
    references: [user.id],
  }),
}));

export const accountRelations = relations(account, ({ one }) => ({
  user: one(user, {
    fields: [account.userId],
    references: [user.id],
  }),
}));

// ---------------------------------------------------------------------------
// Phase-2 listing model (HAND-AUTHORED — see file header). FK-rooted at user.id.
// ---------------------------------------------------------------------------

// Fixed curated enums (D-05/D-08). Declared before the tables that reference them (const TDZ).
export const listingStatus = pgEnum("listing_status", ["draft", "published", "unlisted"]);
export const bookingMode = pgEnum("booking_mode", ["instant", "request"]);
export const spaceType = pgEnum("space_type", [
  "pickleball_court",
  "tennis_court",
  "basketball_court",
  "multi_sport_court",
  "gym_fitness_floor",
  "yoga_studio",
  "dance_studio",
  "pilates_barre_studio",
  "martial_arts_boxing",
  "home_private_gym",
  "multi_purpose_event",
]);

// D-67 host-selected cancellation tier. A brand-new CREATE TYPE — the 55P04 two-migration split
// (0010/0012) applies ONLY to ALTER TYPE ... ADD VALUE on an EXISTING type, so this type and its first
// use may share one migration transaction.
export const cancellationPolicy = pgEnum("cancellation_policy", ["flexible", "standard", "strict"]);

export const listing = pgTable(
  "listing",
  {
    id: text("id").primaryKey(), // app-generated uuid (matches user.id text PK)
    hostId: text("host_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    title: text("title"), // nullable in draft; required at publish (publishSchema)
    description: text("description"),
    primarySpaceType: spaceType("primary_space_type"), // D-05/D-08 canonical primary type
    // Structured address (D-10) — nullable in draft, required at publish.
    addressLine1: text("address_line1"),
    addressLine2: text("address_line2"),
    city: text("city"),
    region: text("region"),
    postalCode: text("postal_code"),
    country: text("country"),
    neighborhood: text("neighborhood"), // approximate-display anchor (D-09)
    // PostGIS point (D-10). AXIS ORDER: x = longitude, y = latitude. Humans say "lat,lng" but
    // PostGIS stores (x=lng, y=lat) — always persist with { x: lng, y: lat } (RESEARCH Pitfall 1).
    location: geometry("location", { type: "point", mode: "xy", srid: 4326 }),
    showExactAddress: boolean("show_exact_address").default(false).notNull(), // D-09 default approximate
    maxOccupancy: integer("max_occupancy"), // D-07 single capacity int
    unitCount: integer("unit_count").default(1).notNull(), // D-21 (1 = exclusive whole-space; N = multi-unit venue)
    timezone: text("timezone").default("Asia/Manila").notNull(), // D-27 (IANA; default launch region — drives calendar display)
    hourlyRateCents: integer("hourly_rate_cents"), // D-03 integer minor units (Pitfall 5)
    dayRateCents: integer("day_rate_cents"), // D-03
    currency: text("currency").default("php").notNull(), // D-46 single-region PHP; column future-proofs multi-region (0008 reconciles + backfills 'usd'→'php')
    bookingMode: bookingMode("booking_mode").default("instant").notNull(), // D-04 stored; D-62 demand-first default flip (was "request"), live-DB default set in drizzle/0011
    // D-77 host-chosen cancellation tier. NO DEFAULT — the wizard requires an explicit choice before
    // publishing (deliberately breaks the D-62 precedent of defaulting to the most booker-friendly option).
    // Nullable so existing DRAFT listings backfill cleanly; the PUBLISH gate enforces non-null, mirroring
    // how bookability is gated rather than creation. Editable while hosting; a retier NEVER rewrites an
    // in-flight booking (booking.cancellationPolicy is the creation-time snapshot, D-67).
    cancellationPolicy: cancellationPolicy("cancellation_policy"),
    status: listingStatus("status").default("draft").notNull(), // D-02/LIST-05
    publishedAt: timestamp("published_at", { withTimezone: true }),
    deletedAt: timestamp("deleted_at", { withTimezone: true }), // soft-delete (Claude's discretion)
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .defaultNow()
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  (t) => [
    index("listing_host_idx").on(t.hostId),
    index("listing_status_idx").on(t.status),
    index("listing_location_gist").using("gist", t.location), // Phase-4 radius search ready
  ],
);

export const listingPhoto = pgTable(
  "listing_photo",
  {
    id: text("id").primaryKey(),
    listingId: text("listing_id")
      .notNull()
      .references(() => listing.id, { onDelete: "cascade" }),
    publicId: text("public_id").notNull(), // Cloudinary public_id — needed for destroy (orphan cleanup)
    url: text("url").notNull(), // secure_url
    position: integer("position").notNull(), // 0 = cover (D-04)
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    index("listing_photo_listing_idx").on(t.listingId),
    uniqueIndex("listing_photo_position_uq").on(t.listingId, t.position), // stable ordering invariant
  ],
);

// Amenities & activity tags as JOIN tables (NOT array columns) — keeps Phase-4 filters
// indexable & clean (D-05/D-06).
export const listingAmenity = pgTable(
  "listing_amenity",
  {
    listingId: text("listing_id")
      .notNull()
      .references(() => listing.id, { onDelete: "cascade" }),
    amenity: text("amenity").notNull(),
  },
  (t) => [uniqueIndex("listing_amenity_uq").on(t.listingId, t.amenity)],
);

export const listingActivityTag = pgTable(
  "listing_activity_tag",
  {
    listingId: text("listing_id")
      .notNull()
      .references(() => listing.id, { onDelete: "cascade" }),
    tag: text("tag").notNull(),
  },
  (t) => [uniqueIndex("listing_activity_tag_uq").on(t.listingId, t.tag)],
);

// Host payout state — a SEPARATE table keyed 1:1 to user (NOT Better Auth additionalFields, to keep
// the auth schema CLI-clean). PayMongo shape (D-20): activation is set ONLY by the Plan-06
// merchant.activated webhook; payoutsEnabled is the provider-agnostic cached gate flag deriveBookable
// reads (KEEP THIS NAME). These flags are webhook/server-set ONLY — never from a client body.
export const hostPayout = pgTable("host_payout", {
  userId: text("user_id")
    .primaryKey()
    .references(() => user.id, { onDelete: "cascade" }),
  paymongoAccountId: text("paymongo_account_id").unique(), // host's PayMongo Linked-Account id
  activationStatus: text("activation_status").default("pending").notNull(), // pending|activated|declined
  payoutsEnabled: boolean("payouts_enabled").default(false).notNull(), // cached gate flag (deriveBookable)
  onboardingComplete: boolean("onboarding_complete").default(false).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .defaultNow()
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
});

// PayMongo webhook idempotency ledger (PAY-04 / T-06-REPLAY). One row per PROCESSED event id; the
// webhook route checks this BEFORE applying an event so a double-delivered / retried PayMongo webhook
// is a no-op (duplicate → 200 skip). Hand-authored (not a Better Auth table); preserve on any auth regen.
export const paymongoEvent = pgTable("paymongo_event", {
  id: text("id").primaryKey(), // the PayMongo event id (data.id) — the idempotency key
  type: text("type").notNull(), // e.g. merchant.activated / merchant.declined
  processedAt: timestamp("processed_at", { withTimezone: true }).defaultNow().notNull(),
});

// Host payout state machine (D-59). SEPARATE from booking_status (line ~277): payout-eligibility is
// DERIVED from confirmed + endsAt, NOT from a `completed` booking transition (D-56/Claude's discretion).
// Peerspace vocabulary: held → processing → paid, plus refunded/failed. Declared before the table it
// backs (const TDZ), mirroring the bookingStatus pgEnum idiom.
export const payoutLedgerState = pgEnum("payout_ledger_state", [
  "held",
  "processing",
  "paid",
  "refunded",
  "failed",
]);

// D-71 ledger row kind. 'payout' = the existing credit transfer; 'host_cancel_fee' = a SIGNED DEBIT
// (negative net_cents) netted against the host's next payout. EVERY pre-existing ledger query must be
// scoped `AND kind = 'payout'` or a debit row trips the payout-reconcile stuck-`held` alert. Declared
// before the table it backs (const TDZ), mirroring the payoutLedgerState idiom above.
export const ledgerKind = pgEnum("ledger_kind", ["payout", "host_cancel_fee"]);

// One row per booking payout (D-51/D-59, RESEARCH Pattern 3). The Plan-05 T+24h sweep INSERTs this row
// with `ON CONFLICT (booking_id, kind) DO NOTHING` as the at-most-once transfer LOCK (same philosophy as
// booking_idem_uq, line ~360) — the (booking_id, kind) UNIQUE is the DB-enforced gate so a booking is paid
// out at most once. Phase 7 (D-71) WIDENED that gate from UNIQUE(booking_id) to UNIQUE(booking_id, kind)
// so a booking can ALSO carry one `host_cancel_fee` debit row; the payout gate itself is unchanged because
// every payout row is kind='payout'. The Plan-04 refund webhook and the HOST-03 page (Plan 06) read/update it. The applied
// commission (rate + amount) is FROZEN here (D-51) so a later rate change never rewrites a past payout.
// All money is integer centavos (Pitfall 5). Hand-authored (not a Better Auth table) — preserve on any
// auth regen; FKs are onDelete:"restrict" (a financial record must never cascade-delete).
export const hostPayoutLedger = pgTable(
  "host_payout_ledger",
  {
    id: text("id").primaryKey(),
    bookingId: text("booking_id")
      .notNull()
      // D-71: the at-most-once gate is now COMPOSITE (booking_id, kind) — see the table-level unique below.
      // A booking can hold at most ONE payout row AND at most ONE host_cancel_fee row.
      .references(() => booking.id, { onDelete: "restrict" }),
    hostId: text("host_id")
      .notNull()
      .references(() => user.id, { onDelete: "restrict" }),
    paymentId: text("payment_id"), // PayMongo pay_... (captured from the payment.paid webhook)
    grossCents: integer("gross_cents").notNull(),
    commissionRateBps: integer("commission_rate_bps").notNull(), // FROZEN rate (D-51)
    commissionCents: integer("commission_cents").notNull(), // FROZEN amount (D-51)
    netCents: integer("net_cents").notNull(), // gross − commission (D-52)
    currency: text("currency").default("php").notNull(),
    state: payoutLedgerState("state").default("held").notNull(),
    // D-71 row kind. Defaults to 'payout' so every pre-Phase-7 row backfills by construction and the
    // widened composite unique is satisfied without a data migration.
    kind: ledgerKind("kind").default("payout").notNull(),
    // D-71: how much of a DEBIT has been netted so far. A debit is only `paid` when recovered_cents == -net_cents.
    recoveredCents: integer("recovered_cents").default(0).notNull(),
    transferId: text("transfer_id"), // PayMongo batch/transfer id (set when the transfer fires)
    paidAt: timestamp("paid_at", { withTimezone: true }), // when processing → paid
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .defaultNow()
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  (t) => [
    index("host_payout_ledger_host_idx").on(t.hostId),
    // D-71 the at-most-once gate, WIDENED from UNIQUE(booking_id). Installed on the live DB by the
    // hand-authored drizzle/0014 constraint swap (Postgres has no ALTER CONSTRAINT for this).
    unique("host_payout_ledger_booking_id_kind_unique").on(t.bookingId, t.kind),
  ],
);

// ---------------------------------------------------------------------------
// Phase-7 notification model (D-86/D-91/D-92). One `notification` row per in-app notification, written
// by the same Inngest function that sends the email so the two channels cannot drift (D-91).
// ---------------------------------------------------------------------------

// D-86 notification kinds. One value per lifecycle event that reaches a human; the NotificationPayload
// union below is keyed on this same discriminant, so adding a value here without handling it in the
// dropdown renderer is a COMPILE error, not a blank row. Declared before the table it backs (const TDZ).
export const notificationType = pgEnum("notification_type", [
  "booking_confirmed",
  "request_received",
  "request_approved",
  "request_declined",
  "new_request_to_host",
  "booking_cancelled_by_booker",
  "booking_cancelled_by_host",
  "refund_issued",
  "reminder_pre_expiry",
  "reminder_pre_session",
  "reminder_pre_sla",
]);

// D-86 durable notification payload. STORE DISPLAY STRINGS, NEVER IDS TO JOIN AT READ TIME: a notification
// saying "Your booking at Court A was cancelled" must not silently re-render if the listing is later
// retitled — D-86 explicitly wants history that survives the underlying booking changing state. It also
// makes the dropdown a single indexed table scan with no joins.
//
// PRIVACY (T-07-04): display strings ONLY — no email addresses, no payment ids, no bank/account details.
// Every time label is composed venue-local by the caller (the `composeWhenLabel` idiom); these payloads
// never carry a raw Date.
//
// D-91 SUFFICIENCY RULE (07-07): this payload is the SOLE input to BOTH channels — the in-app row AND the
// email `sendForType` dispatches (src/inngest/functions/notify.ts). A field the email needs therefore
// belongs HERE, not in a second parallel structure; one event feeding two channels is exactly what D-91
// buys, and a second source would reintroduce the drift it exists to prevent. `referenceLabel`,
// `totalLabel` on new_request_to_host, and `expired` were added for that reason.
export type NotificationPayload =
  | {
      type: "booking_confirmed";
      listingTitle: string;
      whenLabel: string;
      totalLabel: string;
      /** The FIT-XXXXXXXX booking reference, as displayed. Required by sendBookingConfirmed (D-91). */
      referenceLabel: string;
      href: string;
    }
  | { type: "request_received"; listingTitle: string; whenLabel: string; totalLabel: string; href: string }
  | {
      type: "request_approved";
      listingTitle: string;
      whenLabel: string;
      totalLabel: string;
      payByLabel: string;
      href: string;
    }
  | {
      type: "request_declined";
      listingTitle: string;
      whenLabel: string;
      reasonLabel?: string;
      /** COPY VARIANT, not a display string: true ⇒ "expired before the host responded", false ⇒ "the host
       *  couldn't take it". Two different sentences, not two values of one sentence, so it cannot be a
       *  label. sendRequestDeclined's `opts.expired` reads it (D-91 sufficiency rule above). */
      expired: boolean;
      href: string;
    }
  | {
      type: "new_request_to_host";
      listingTitle: string;
      whenLabel: string;
      bookerLabel: string;
      /** The server-frozen guest-pays amount, as displayed. Required by sendNewRequestToHost (D-91). */
      totalLabel: string;
      respondByLabel: string;
      href: string;
    }
  | {
      type: "booking_cancelled_by_booker";
      listingTitle: string;
      whenLabel: string;
      bookerLabel: string;
      href: string;
    }
  | {
      type: "booking_cancelled_by_host";
      listingTitle: string;
      whenLabel: string;
      refundLabel: string;
      /** WR-04 (07-17) — the AUDIENCE of this copy. cancelBookingAsHost emits to BOTH parties; the host's
       *  copy must state the host's situation (you cancelled; your guest is refunded; the fee), never the
       *  booker's. REQUIRED on every new write. Durable pre-07-17 jsonb rows lack this field — renderers
       *  treat anything !== "host" (including undefined) as booker, so old rows keep their meaning. */
      side: "booker" | "host";
      /** Present ONLY on the host side AND only when the charged D-71 fee > 0 — a "₱0 fee" claim would be
       *  CR-01's disease in a new place. formatMoney output, composed by the emitter. */
      feeLabel?: string;
      href: string;
    }
  | { type: "refund_issued"; listingTitle: string; whenLabel: string; refundLabel: string; href: string }
  | {
      type: "reminder_pre_expiry";
      listingTitle: string;
      whenLabel: string;
      totalLabel: string;
      payByLabel: string;
      href: string;
    }
  | { type: "reminder_pre_session"; listingTitle: string; whenLabel: string; href: string }
  | {
      type: "reminder_pre_sla";
      listingTitle: string;
      whenLabel: string;
      bookerLabel: string;
      respondByLabel: string;
      href: string;
    };

export const notification = pgTable(
  "notification",
  {
    id: text("id").primaryKey(),
    recipientId: text("recipient_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    type: notificationType("type").notNull(),
    // Denormalised for the dropdown's deep link + for cheap filtering. Nullable: not every notification
    // is booking-scoped.
    bookingId: text("booking_id").references(() => booking.id, { onDelete: "cascade" }),
    payload: jsonb("payload").$type<NotificationPayload>().notNull(),
    readAt: timestamp("read_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    // Unread count — the hot query, on EVERY page render. PARTIAL index: only unread rows are indexed,
    // so it stays tiny forever while read history grows without bound. Do NOT add a denormalised counter
    // on `user` — that is a second writer and a drift class for an already-indexed query.
    index("notification_unread_idx").on(t.recipientId).where(sql`read_at IS NULL`),
    // Dropdown list — newest first, scoped to the recipient.
    index("notification_recipient_created_idx").on(t.recipientId, t.createdAt.desc()),
  ],
);

// D-85 the four reminder kinds. Declared before the table it backs (const TDZ).
export const reminderKind = pgEnum("reminder_kind", [
  "pre_expiry",
  "pre_session_booker",
  "pre_session_host",
  "pre_sla_host",
]);

// D-87 at-most-once reminder claim. The UNIQUE(booking_id, kind) IS the lock — the same DB-level
// guarantee host_payout_ledger's UNIQUE(booking_id) provides for payouts. Inngest's own idempotency is
// a 24-HOUR key that is documented as bypassed by debouncing, batching and function pausing; it is a
// structural mismatch for "exactly one reminder, ever" and must NOT be relied on. The reminder cron
// INSERTs ... ON CONFLICT DO NOTHING RETURNING id and sends ONLY on a non-empty return.
export const bookingReminder = pgTable(
  "booking_reminder",
  {
    id: text("id").primaryKey(),
    bookingId: text("booking_id")
      .notNull()
      .references(() => booking.id, { onDelete: "cascade" }),
    kind: reminderKind("kind").notNull(),
    sentAt: timestamp("sent_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [uniqueIndex("booking_reminder_uq").on(t.bookingId, t.kind)],
);

// ---------------------------------------------------------------------------
// Phase-3 availability model (HAND-AUTHORED — the double-booking keystone, D-21/D-28).
// operating_hours (recurring weekly windows), availability_block (close-only overrides), and
// booking (the occupancy table). The GiST EXCLUDE that makes overlaps structurally impossible
// lives in drizzle/0005_booking_exclusion.sql — Drizzle CANNOT express EXCLUDE (see `booking`).
// ---------------------------------------------------------------------------

// Booking-status enum. Declared before `booking` (const TDZ), mirroring listingStatus (line 135).
// Phase 3 referenced ONLY 'pending'/'confirmed' (the 0005 partial WHERE occupying set). Phase 6 adds
// the two request-to-book slot-holding states 'requested' (booker asked; host not yet approved) and
// 'approved' (host approved; awaiting the booker's payment). BOTH occupy the slot exactly like
// pending/confirmed, so the booking_no_overlap GiST EXCLUDE (drizzle/0012) AND every read/occupancy
// predicate MUST include them, or a requested/approved slot would fail to block a double-booking
// (D-63 correctness). The live-DB ADD VALUE is migration drizzle/0010 — split from its first USE
// (the widened EXCLUDE WHERE in 0012) because Postgres cannot ADD VALUE and USE it in one transaction
// (Pitfall 2). Postgres appends ADD VALUE at the enum tail, so declare requested/approved LAST to match.
export const bookingStatus = pgEnum("booking_status", [
  "pending",
  "confirmed",
  "cancelled",
  "declined",
  "completed",
  "requested",
  "approved",
]);

// D-70/D-79 who initiated a cancellation. Display/audit metadata only — the non-repudiable record is the
// `recordAudit` row written by the cancel actions. Declared before `booking` (const TDZ).
export const cancelledBy = pgEnum("cancelled_by", ["booker", "host", "system"]);

// Recurring weekly operating hours (AVAIL-01, D-25). Multiple windows/day = multiple rows with the
// same (listingId, dayOfWeek). Hours are listing-wide (all units share). Times are venue-local wall
// clock (Postgres `time`, no tz) — combine with a concrete venue-local date via TZDate for a UTC instant.
export const operatingHours = pgTable(
  "operating_hours",
  {
    id: text("id").primaryKey(),
    listingId: text("listing_id")
      .notNull()
      .references(() => listing.id, { onDelete: "cascade" }),
    dayOfWeek: integer("day_of_week").notNull(), // 0=Sun..6=Sat (JS Date.getDay convention, A1)
    openTime: time("open_time").notNull(), // venue-local wall clock
    closeTime: time("close_time").notNull(), // must be > openTime (server-validated; no midnight cross v1)
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [index("operating_hours_listing_idx").on(t.listingId)],
);

// Close-only availability overrides (AVAIL-02, D-24). unit NULL = whole listing blocked; else one
// unit. A block is subtractive in the read model; "unblock" = delete the row. Block-vs-booking is NOT
// DB-enforced here (Open Question Q1 RESOLVED) — the Phase-4 server action guards it in-transaction.
export const availabilityBlock = pgTable(
  "availability_block",
  {
    id: text("id").primaryKey(),
    listingId: text("listing_id")
      .notNull()
      .references(() => listing.id, { onDelete: "cascade" }),
    unit: integer("unit"), // NULL = whole listing; else one unit (D-24)
    startsAt: timestamp("starts_at", { withTimezone: true }).notNull(),
    endsAt: timestamp("ends_at", { withTimezone: true }).notNull(),
    reason: text("reason"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [index("availability_block_listing_idx").on(t.listingId)],
);

// The occupancy table + the double-booking keystone (D-21/D-28, SC#4). Each booking reserves exactly
// ONE unit (bare index 1..unitCount) for its [startsAt, endsAt) window.
//
// EXCLUDE "booking_no_overlap" is HAND-AUTHORED in drizzle/0005_booking_exclusion.sql — Drizzle
// cannot express EXCLUDE (issues #2813/#3388). `drizzle-kit generate` will NOT produce it; never
// assume the constraint exists from THIS file alone. Phase 6 (D-63) WIDENS the occupying-status set to
// {pending, confirmed, requested, approved} so a requested/approved (request-to-book) slot also blocks a
// conflicting booking. The constraint is DROPped + re-ADDed in drizzle/0012_booking_exclusion_v2.sql
// (Postgres has no ALTER CONSTRAINT ... WHERE). NOTE the 0012 predicate is written as the SET-EQUIVALENT
// complement `WHERE status NOT IN ('cancelled','declined','completed')` — not the positive four-status
// list — because drizzle-orm's migrator runs all pending migrations in ONE transaction, and naming the
// enum values 'requested'/'approved' (ADDed in 0010) in that same transaction would raise 55P04 on an
// already-migrated DB. The GiST EXCLUDE is the SOLE double-booking authority — every read/occupancy
// predicate must mirror this occupying set (pending/confirmed/requested/approved).
//
// Phase-4 adds the pending-hold lifecycle columns (expiresAt/quotedTotalCents/currency/idempotencyKey)
// + the booking_idem_uq partial-unique index. Unlike EXCLUDE, these ARE Drizzle-expressible and go
// through `drizzle-kit generate` (drizzle/0006_booking_hold.sql) — only the EXCLUDE stays hand-authored.
export const booking = pgTable(
  "booking",
  {
    id: text("id").primaryKey(),
    listingId: text("listing_id")
      .notNull()
      .references(() => listing.id, { onDelete: "cascade" }),
    unit: integer("unit").notNull(), // bare index 1..unitCount (D-21)
    bookerId: text("booker_id")
      .notNull()
      .references(() => user.id, { onDelete: "restrict" }), // A5 — bookings are financial records; never cascade-delete
    startsAt: timestamp("starts_at", { withTimezone: true }).notNull(),
    endsAt: timestamp("ends_at", { withTimezone: true }).notNull(),
    // WR-05: default to the SAFE state 'pending', not 'confirmed'. Now that the payout sweep pays out
    // 'confirmed' bookings past ends_at + delay, a 'confirmed' default would let any insert that omits
    // `status` mint a slot-occupying, payout-eligible booking that was never paid for. 'pending' is the
    // fail-safe default; every real caller sets `status` explicitly (holds are inserted 'pending'; the
    // payment.paid webhook is the sole confirm authority). Live DB default changed in drizzle/0009.
    status: bookingStatus("status").default("pending").notNull(),
    // D-61 creation-time booking-mode SNAPSHOT (display/audit only — lifecycle correctness rests on
    // `status`, NOT this column). Nullable, no default, no backfill: existing bookings predate the
    // request-to-book fork. Captured at creation so a later listing.bookingMode edit (D-62/D-61: the mode
    // governs NEW bookings only, in-flight requests keep their original mode) never rewrites an
    // in-flight booking's mode. Live-DB ADD COLUMN is drizzle/0011 (backfill-free, mirrors 0006).
    bookingMode: bookingMode("booking_mode"),
    // Pending-hold lifecycle (D-49, Phase 4). All new columns are nullable-safe — there are no existing
    // booking rows in dev/UAT (A7) — so 0006 is a backfill-free ADD COLUMN.
    expiresAt: timestamp("expires_at", { withTimezone: true }), // hold TTL; only meaningful while 'pending' (NULL once confirmed/terminal). D-48 lazy expiry treats a past value as FREE.
    quotedTotalCents: integer("quoted_total_cents"), // price frozen at hold time (Phase-5 charge integrity, D-49)
    currency: text("currency").default("php").notNull(), // freeze the display/charge currency (D-46)
    idempotencyKey: text("idempotency_key"), // nullable client token — double-click backstop (D-42)
    // PayMongo pay_... captured by the Plan-04 payment.paid webhook at confirm, so a later refund
    // (Plan 04 refund mechanism / D-58 auto-refund backstop) can reference the payment. Nullable
    // ADD COLUMN (backfill-free — no existing booking rows, A7).
    paymentId: text("payment_id"),
    // The PAYMENT RAIL the booker actually used ("card" / "gcash" / "paymaya" / "qrph" / "dob_ubp" / …),
    // captured by the same payment.paid webhook that captures paymentId, from the SAME verified event
    // resource (never a client field). Phase-7 addition (07-09).
    //
    // WHY IT MUST BE PERSISTED. `isApiRefundable` (src/lib/payments/refund-rail.ts) is the SOLE predicate
    // deciding whether a refund can be dispatched through the PayMongo API at all — QRPh and UBP cannot be
    // (Pitfall 1), and the predicate FAILS CLOSED. The gone-slot backstop reads the rail off the live
    // webhook event, but a booker CANCELLATION happens hours or days later with no event in hand, so
    // without this column the predicate would receive `undefined` on every cancellation, answer "not
    // refundable", and route EVERY refund to the operator-alert path — the money would never move. The
    // rail is a durable property of the payment, so it is stored alongside the payment id it belongs to.
    //
    // Nullable + backfill-free. A pre-Phase-7 confirmed booking has no rail recorded; `isApiRefundable`
    // reads that as non-refundable and takes the operator-alert path, which is the correct fail-closed
    // outcome for a payment whose rail we genuinely do not know.
    paymentMethod: text("payment_method"),
    // ---- Phase-7 cancellation + fee split (D-67/D-69/D-74/D-79). ALL nullable / defaulted, so this is a
    // backfill-free ADD COLUMN for every column except the two the 0014 hand-edit backfills.
    // STRUCTURALLY INERT for occupancy: none of these columns appears in the booking_no_overlap GiST EXCLUDE
    // predicate (listing_id, unit, starts_at, ends_at, status), the in-tx stale-hold sweep, or the cron expiry
    // sweep. D-79 keeps the SINGLE `cancelled` status precisely so the EXCLUDE predicate never changes: that
    // predicate is the COMPLEMENT (`status NOT IN ('cancelled','declined','completed')`), so any NEW status
    // value would default to OCCUPYING and permanently block the slot of every partially-refunded cancellation.
    //
    // D-67 creation-time cancellation-tier SNAPSHOT, mirroring bookingMode above. A host retiering the
    // listing NEVER rewrites the refund terms of an in-flight booking.
    cancellationPolicy: cancellationPolicy("cancellation_policy"),
    // Finding 2 — the PAYOUT basis. quoted_total_cents stays the CHARGE basis (all-in, what PayMongo charged
    // and what a refund references). Paying out 90% of quoted_total would hand the host 90% of the platform's
    // own service fee, inverting the entire purpose of D-74.
    spacePriceCents: integer("space_price_cents"),
    // D-74 platform revenue, NON-REFUNDABLE. quoted_total_cents = space_price_cents + service_fee_cents.
    serviceFeeCents: integer("service_fee_cents").default(0),
    // D-79 what actually went back to the booker (space refund only — the service fee is never refunded).
    refundCents: integer("refund_cents"),
    // D-69 the RETAINED space price. Becomes the payout gross: host receives retained − 10% commission.
    retainedSpaceCents: integer("retained_space_cents"),
    cancelledBy: cancelledBy("cancelled_by"),
    cancelledAt: timestamp("cancelled_at", { withTimezone: true }),
    // D-93: distinguishes "declined because too close to start" from "declined because the SLA lapsed", read
    // by the email/notification composer so both sides get an honest message.
    declineReason: text("decline_reason"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    index("booking_listing_idx").on(t.listingId),
    // MANAGE-01 /bookings read path: filter by booker, newest session first.
    index("booking_booker_idx").on(t.bookerId, t.startsAt.desc()),
    // Partial-unique idempotency index (D-42 / RESEARCH Pattern 6): at most one booking per client token.
    // Drizzle CAN express a partial unique index via .where() (same idiom as listing_photo_position_uq);
    // scoping to non-NULL keys lets the many holds placed without a token coexist.
    uniqueIndex("booking_idem_uq").on(t.idempotencyKey).where(sql`idempotency_key IS NOT NULL`),
  ],
);

export const listingRelations = relations(listing, ({ one, many }) => ({
  host: one(user, {
    fields: [listing.hostId],
    references: [user.id],
  }),
  photos: many(listingPhoto),
  amenities: many(listingAmenity),
  activityTags: many(listingActivityTag),
  operatingHours: many(operatingHours),
  blocks: many(availabilityBlock),
  bookings: many(booking),
}));

export const operatingHoursRelations = relations(operatingHours, ({ one }) => ({
  listing: one(listing, {
    fields: [operatingHours.listingId],
    references: [listing.id],
  }),
}));

export const availabilityBlockRelations = relations(availabilityBlock, ({ one }) => ({
  listing: one(listing, {
    fields: [availabilityBlock.listingId],
    references: [listing.id],
  }),
}));

export const bookingRelations = relations(booking, ({ one }) => ({
  listing: one(listing, {
    fields: [booking.listingId],
    references: [listing.id],
  }),
  booker: one(user, {
    fields: [booking.bookerId],
    references: [user.id],
  }),
}));
