-- WR-06-DURABLE (quick task 260806-p3y) — the DURABLE AUDIT SINK. GENERATED by `drizzle-kit generate`, not
-- hand-authored: a plain table with a partial btree index is fully Drizzle-expressible, so it goes through
-- the generator (the schema.ts rule — only the GiST EXCLUDE stays hand-written), which also keeps
-- drizzle/meta/_journal.json and 0024_snapshot.json consistent for `npm run db:migrate`.
--
-- PURELY ADDITIVE: a brand-new table. It touches no existing row, no existing column, and no existing
-- constraint, so there is nothing to backfill and nothing that can fail on live data.
--
-- WHAT THE TABLE IS FOR: recordAudit (src/lib/audit.ts) shipped as a console-only sink by documented v1
-- design. This closes that tradeoff so the `outcome = 'needs_attention'` money seams — failed auto-refunds,
-- the QRPh unrefundable-rail manual-refund alert, refund_after_payout, stranded checkout sessions — become
-- a queryable operator queue instead of a log grep. On the qrph rail those rows are real held money.
--
-- The partial index IS the operator query: every unresolved needs_attention, newest first. It mirrors
-- notification_unread_idx (drizzle/0013) — indexing only the OPEN rows keeps it tiny forever while resolved
-- history grows without bound. `actor_id` deliberately carries NO FK: 8 of the 57 call sites pass the
-- literal "system"/"guest", including the QRPh alert, and an FK would reject exactly those rows.
--
-- Unqualified table name (the generator's dialect default here) so tests/helpers/db.ts replays it into
-- every isolated test schema.
CREATE TABLE "audit" (
	"id" text PRIMARY KEY NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"actor_id" text NOT NULL,
	"action" text NOT NULL,
	"outcome" text NOT NULL,
	"meta" jsonb,
	"resolved_at" timestamp with time zone
);
--> statement-breakpoint
CREATE INDEX "audit_needs_attention_idx" ON "audit" USING btree ("created_at" DESC NULLS LAST) WHERE outcome = 'needs_attention' AND resolved_at IS NULL;