// DO NOT EDIT — generated by scripts/generate-design-tokens.mjs.
// Run `npm run design:tokens` to regenerate; tests/design/token-drift.test.ts fails on any diff.
//
// DS-12 / D-18 — the ONLY sanctioned duplicate of a design-token value in this repository.
//
// WHY A DUPLICATE IS ALLOWED TO EXIST AT ALL. Nearly everything in this app paints through CSS
// and reads these custom properties directly, which is why there is no other copy anywhere. A
// few consumers genuinely cannot read CSS: an inline SVG string handed to a mapping library, a
// document-level error page that renders before the stylesheet, an HTML email. They need a
// literal — and a literal typed by hand drifts. It already had: the single-listing map carried a
// coral that stopped matching --brand when that token was re-derived for contrast, and nothing
// in the repository could tell. Import from here instead of writing a hex.
//
// THIS FILE SITS OUTSIDE THE DESIGN GATE'S SCANNED TREE ON PURPOSE. src/app/** and
// src/components/** are scanned for raw colour values; src/lib/design/** is not. That asymmetry
// is the whole design: the hex literals below are legal precisely because they are generated,
// checked against the stylesheet on every test run, and unreachable by hand-editing without a
// red test.
//
// ONLY COLOUR TOKENS APPEAR HERE. Both theme blocks also declare type, radius, elevation and
// motion values, none of which has a hex. A key is included when its declared value is a single
// oklch() call and nothing else — which is also why the elevation steps are absent: a shadow
// shorthand CONTAINS a colour, it is not one.
//
// KEYS ARE SORTED by UTF-16 code unit rather than kept in stylesheet order, and never with a
// locale-aware comparator, because the drift check asserts byte equality and a locale-aware sort
// is machine-dependent.

/** One token: the value `globals.css` authored, and its 8-bit sRGB equivalent. */
export type TokenValue = { readonly oklch: string; readonly hex: string };

/** The themes the stylesheet declares, in source order. */
export const THEME_NAMES = ["court", "grove"] as const;

/**
 * Every colour token of every theme, keyed by the custom-property name EXACTLY as it appears in
 * `globals.css` — leading `--` included, so a reader can grep one string across the stylesheet,
 * this module and every consumer.
 *
 * The theme union is spelled out rather than derived from THEME_NAMES so the type a consumer
 * hovers is the two literal names, not an indirection.
 */
export const THEME_TOKENS: Record<"court" | "grove", Record<string, TokenValue>> = {
  court: {
    "--accent": { oklch: "oklch(0.97 0 0)", hex: "#f5f5f5" },
    "--accent-foreground": { oklch: "oklch(0.205 0 0)", hex: "#171717" },
    "--background": { oklch: "oklch(1 0 0)", hex: "#ffffff" },
    "--border": { oklch: "oklch(0.922 0 0)", hex: "#e5e5e5" },
    "--brand": { oklch: "oklch(0.58 0.208 25)", hex: "#da2d34" },
    "--brand-foreground": { oklch: "oklch(0.985 0 0)", hex: "#fafafa" },
    "--card": { oklch: "oklch(1 0 0)", hex: "#ffffff" },
    "--card-foreground": { oklch: "oklch(0.145 0 0)", hex: "#0a0a0a" },
    "--destructive": { oklch: "oklch(0.535 0.215 27.325)", hex: "#cd0916" },
    "--destructive-foreground": { oklch: "oklch(0.985 0 0)", hex: "#fafafa" },
    "--foreground": { oklch: "oklch(0.145 0 0)", hex: "#0a0a0a" },
    "--input": { oklch: "oklch(0.922 0 0)", hex: "#e5e5e5" },
    "--muted": { oklch: "oklch(0.97 0 0)", hex: "#f5f5f5" },
    "--muted-foreground": { oklch: "oklch(0.53 0 0)", hex: "#6c6c6c" },
    "--popover": { oklch: "oklch(1 0 0)", hex: "#ffffff" },
    "--popover-foreground": { oklch: "oklch(0.145 0 0)", hex: "#0a0a0a" },
    "--primary": { oklch: "oklch(0.205 0 0)", hex: "#171717" },
    "--primary-foreground": { oklch: "oklch(0.985 0 0)", hex: "#fafafa" },
    "--ring": { oklch: "oklch(0.45 0 0)", hex: "#555555" },
    "--secondary": { oklch: "oklch(0.97 0 0)", hex: "#f5f5f5" },
    "--secondary-foreground": { oklch: "oklch(0.205 0 0)", hex: "#171717" },
    "--success": { oklch: "oklch(0.58 0.15 150)", hex: "#1b9247" },
    "--success-foreground": { oklch: "oklch(0.985 0 0)", hex: "#fafafa" },
  },
  grove: {
    "--accent": { oklch: "oklch(0.958 0.01 190)", hex: "#eaf3f2" },
    "--accent-foreground": { oklch: "oklch(0.24 0.03 190)", hex: "#0c2422" },
    "--background": { oklch: "oklch(0.988 0.006 190)", hex: "#f7fcfc" },
    "--border": { oklch: "oklch(0.905 0.012 190)", hex: "#d7e2e1" },
    "--brand": { oklch: "oklch(0.5445 0.09 190)", hex: "#13807c" },
    "--brand-foreground": { oklch: "oklch(0.985 0.004 190)", hex: "#f7fbfb" },
    "--card": { oklch: "oklch(1 0 0)", hex: "#ffffff" },
    "--card-foreground": { oklch: "oklch(0.17 0.02 190)", hex: "#051211" },
    "--destructive": { oklch: "oklch(0.535 0.215 27.325)", hex: "#cd0916" },
    "--destructive-foreground": { oklch: "oklch(0.985 0.004 190)", hex: "#f7fbfb" },
    "--foreground": { oklch: "oklch(0.17 0.02 190)", hex: "#051211" },
    "--input": { oklch: "oklch(0.905 0.012 190)", hex: "#d7e2e1" },
    "--muted": { oklch: "oklch(0.958 0.01 190)", hex: "#eaf3f2" },
    "--muted-foreground": { oklch: "oklch(0.5 0.015 190)", hex: "#5a6665" },
    "--popover": { oklch: "oklch(1 0 0)", hex: "#ffffff" },
    "--popover-foreground": { oklch: "oklch(0.17 0.02 190)", hex: "#051211" },
    "--primary": { oklch: "oklch(0.24 0.03 190)", hex: "#0c2422" },
    "--primary-foreground": { oklch: "oklch(0.985 0.004 190)", hex: "#f7fbfb" },
    "--ring": { oklch: "oklch(0.45 0.02 190)", hex: "#495958" },
    "--secondary": { oklch: "oklch(0.958 0.01 190)", hex: "#eaf3f2" },
    "--secondary-foreground": { oklch: "oklch(0.24 0.03 190)", hex: "#0c2422" },
    "--success": { oklch: "oklch(0.58 0.15 150)", hex: "#1b9247" },
    "--success-foreground": { oklch: "oklch(0.985 0.004 190)", hex: "#f7fbfb" },
  },
};
