// CROP-01 — THE CROP STAGE, MEASURED IN A REAL BROWSER, BECAUSE THERE IS NOWHERE ELSE IT EXISTS.
//
// ═════════════════════════════════════════════════════════════════════════════════════════════════
// WHY THIS FILE EXISTS AT ALL, AND WHY A VITEST SPEC COULD NOT HAVE STOOD IN FOR IT
// ═════════════════════════════════════════════════════════════════════════════════════════════════
//
// `react-easy-crop@6.2.3` renders the crop-area element — the one carrying `tabIndex`, the
// `aria-label`, the round mask and the scrim — ONLY when `this.state.cropSize` is truthy, and
// `cropSize` is set only by `computeSizes()`, which needs a non-zero `containerRef
// .getBoundingClientRect()` AND a decoded `<img>` reporting real naturals.
//
// Probed jsdom 29.1.1 (16-RESEARCH § E) has NEITHER: `getContext("2d")` → `null`;
// `createImageBitmap`, `OffscreenCanvas`, `ResizeObserver`, `URL.createObjectURL` and
// `Image.prototype.decode` → all `undefined`; and every `getBoundingClientRect()` → zeros.
//
//   ⚠ IN JSDOM THE CROP STAGE DOES NOT EXIST IN THE DOM. Not "renders differently" — is absent.
//
// So everything geometric, gestural or pixel-bearing is Playwright or a human, and this file is the
// Playwright half's foundation. The repo has stubbed `ResizeObserver` five times and has NEVER
// stubbed `getBoundingClientRect`; two specs record in prose that they refuse to pretend jsdom has
// layout. This file is the other side of that refusal — the measurements those specs declined to
// fake, taken where they are real.
//
// ═════════════════════════════════════════════════════════════════════════════════════════════════
// TWO CONVENTIONS THIS FILE INTRODUCES, BECAUSE NOTHING IN `e2e/` HAD EITHER
// ═════════════════════════════════════════════════════════════════════════════════════════════════
//
// (1) DRIVING A FILE INPUT. `grep -rn "setInputFiles" e2e/` returned NOTHING before this file. The
//     avatar picker is the only `<input type="file">` in `src/`, it is `className="hidden"`, and it
//     is deliberately unregistered with react-hook-form. `locator.setInputFiles()` sets a hidden
//     input's `files` and dispatches `change`, which is the whole of what the shipped
//     `onAvatarChange` needs — so the bytes fed to the four guards and to the browser's own decoder
//     are the committed `e2e/fixtures/` bytes, generated by `scripts/generate-image-fixtures.mjs`
//     and gated byte-for-byte by `tests/design/image-fixtures.test.ts`. A real decoder on real
//     committed bytes is what makes the `corrupt.jpg` case honest; plan 16-10's jsdom version had to
//     mock `measureImage`, so what it proved was that the branch existed, not that it fires.
//
// (2) READING COMPUTED STYLE. `page.evaluate((el) => getComputedStyle(el)...)` answers cascade
//     questions no source scan can. The library injects its own stylesheet UNLAYERED into the
//     document head while Tailwind v4 utilities live in a cascade layer, and unlayered beats
//     layered — so "the class is in the source" and "the rule wins" are different claims here, and
//     only the second one is a behaviour. Every computed-style assertion below is a VERIFICATION of
//     a rule the library already ships, never a re-authoring of one.
//
// ═════════════════════════════════════════════════════════════════════════════════════════════════
// ⚠ THIS FILE DOES NOT DISCHARGE CROP-04. IT PRODUCES EVIDENCE FOR CROP-01.
// ═════════════════════════════════════════════════════════════════════════════════════════════════
//
// **D-175** rules that CROP-04 is discharged by a PM hardware walk on {iOS Safari, Android Chrome}
// and that planning must not claim it from a Playwright run. The mechanics agree with the decision.
// Four things this run cannot reach, named rather than waved at:
//
//   1. SAFARI'S `gesturestart` / `gesturechange` PATH. `componentDidMount` wires those up
//      separately from the two-finger touch path (16-RESEARCH § A3) — a genuinely different branch
//      of the library — and no emulator fires them. Chromium here never executes that code.
//   2. FINGER OCCLUSION of a stage that is ~227px on a 320px phone. A synthesised touch has no
//      fingertip in front of the thing being framed.
//   3. iOS MOMENTUM AND RUBBER-BANDING. `touch-action: none` asserted below is the mechanism; what
//      it feels like against a scrolling sheet on a real phone is not a computed value.
//   4. THE OS FILE PICKER — which is exactly where D-174's re-pick bug lives. `setInputFiles` sets
//      the input's value programmatically; it is not the event sequence a native picker produces.
//
// The re-pick case below therefore carries its own caveat, and the hardware walk is plan 16-16.
//
// ═════════════════════════════════════════════════════════════════════════════════════════════════
// A DEFECT ON THIS SURFACE THAT IS NOT THIS FILE'S TO FIX, AND WHAT IT COSTS THE LOCATORS
// ═════════════════════════════════════════════════════════════════════════════════════════════════
//
// The zoom slider ships with NO ACCESSIBLE NAME (`deferred-items.md` D1, measured by plan 16-10,
// assigned to plan 16-14). The element carrying `role="slider"` is Radix's THUMB; the dialog's
// `aria-label={AVATAR_ZOOM_LABEL}` lands on the Root, which renders a `<span>` with no role and so
// contributes no name to anything. `getByRole("slider", { name: "Zoom" })` matches ZERO elements
// today.
//
// So every slider locator below is `getByRole("slider")` UNNAMED, scoped to the dialog. That is
// correct-but-loose on purpose: this file does not fix the defect, does not assert that the name is
// fine, and does not encode the broken state as an expectation. ⚠ WHEN 16-14 NAMES THE THUMB, THESE
// LOCATORS SHOULD TIGHTEN TO `getByRole("slider", { name: AVATAR_ZOOM_LABEL })` — one edit per
// locator, and the scoping to `dialog` becomes redundant rather than load-bearing.
//
// ─────────────────────────────────────────────────────────────────────────────────────────────────
// SELECTORS: ZERO NEW TEST HOOKS, AND ZERO VENDOR INTERNALS (Delta-18)
// ─────────────────────────────────────────────────────────────────────────────────────────────────
//
// The stage is addressed by its accessible name, `AVATAR_POSITION_LABEL`, which is the same string a
// screen reader announces — so an assertion that passes is also evidence the stage is announceable.
//
// The library bakes two test ids of its own into its DOM — one on the crop area, one on the
// container. They are VENDOR INTERNALS that no inventory governs, and nothing here reaches for
// either. ⚠ THEY ARE DESCRIBED HERE RATHER THAN SPELLED, deliberately: this plan's acceptance
// criteria grep this file for those exact identifiers and expect zero, so a comment saying "we do
// not use them" that quoted them would be the thing that failed the check. `src/lib/avatar.ts`'s
// header and plan 16-08's rejected-decode-API paragraph set the same precedent for the same reason.
//
// The two ancestors this file needs (the library's container, and our own stage wrapper) are reached
// by walking UP from the named element, so the only string in the whole chain is one the product
// owns.

import { expect, test, type Locator, type Page } from "@playwright/test";
import path from "node:path";

import { BASE, signUpAndReachProfile } from "./helpers/avatar-session";
// The copy literals are IMPORTED, never re-typed (rule F2). A spec carrying its own copy of a
// sentence goes green the day the real one changes — `overflow-320.spec.ts` states the same rule for
// `SUPPORT_EMAIL`, and `src/lib/avatar.ts` is directive-free precisely so a gate can read it.
import { AVATAR_POSITION_LABEL } from "../src/lib/avatar";

// ═════════════════════════════════════════════════════════════════════════════════════════════════
// FIXTURES AND HANDLES
// ═════════════════════════════════════════════════════════════════════════════════════════════════

/** `<root>/e2e/fixtures` — the committed, generator-produced bytes. See `e2e/fixtures/README.md`. */
const FIXTURES = path.join(__dirname, "fixtures");

const fixture = (name: string): string => path.join(FIXTURES, name);

/**
 * Hand a fixture to the shipped picker.
 *
 * `input[type="file"]` is unambiguous by construction — `avatar-field.tsx` records that it is the
 * only one in `src/` — so Playwright's strict mode is the assertion that it stays that way.
 */
async function pick(page: Page, name: string): Promise<void> {
  await page.locator('input[type="file"]').setInputFiles(fixture(name));
}

/**
 * Wait for every running CSS animation in the document to finish before measuring anything.
 *
 * ⚠ NOT A SLEEP, AND NOT OPTIONAL — IT WAS MEASURED. `ui/dialog.tsx:73` puts
 * `data-open:animate-in data-open:zoom-in-95 duration-100` on `DialogContent`, which is a SCALE, and
 * `boundingBox()` reports the TRANSFORMED rect. Probed 2026-08-25 without this call: the 1280x800
 * stage measured **319.7356872558594px** rather than 320 — a box caught at ~99.9% of the way through
 * a 100ms zoom. It passed the 1px band by 0.26px, which is the worst possible outcome: a geometry
 * assertion whose margin is a race rather than a tolerance.
 *
 * `document.getAnimations()` returns the live CSS animations (tailwindcss-animate compiles
 * `animate-in` to a keyframe animation, not a transition), so awaiting their `finished` promises
 * waits for exactly the thing in the way and nothing else. `.catch()` swallows the rejection an
 * animation raises if it is cancelled mid-flight — a cancelled animation is a settled one for this
 * purpose.
 */
async function settleAnimations(page: Page): Promise<void> {
  await page.evaluate(() =>
    Promise.all(document.getAnimations().map((a) => a.finished.catch(() => undefined))),
  );
}

/** The crop stage: the element the library gives `tabIndex`, the round mask, and our label. */
const stageOf = (page: Page): Locator => page.getByLabel(AVATAR_POSITION_LABEL);

/**
 * The library's own container — `.reactEasyCrop_Container`, reached by walking UP from the named
 * stage rather than by its class, so no vendor string appears in a selector.
 */
const containerOf = (page: Page): Locator => stageOf(page).locator("xpath=..");

/**
 * OUR stage wrapper — the `relative … size-[min(320px,100vw-2rem,40dvh)]` box that Delta-2 derives.
 * The container above is `position: absolute; inset: 0` with no intrinsic size, so this is the
 * element that decides how big the stage is.
 */
const wrapperOf = (page: Page): Locator => stageOf(page).locator("xpath=../..");

/** Either overlay, addressed by role. `data-testid="responsive-dialog"` is the pattern's own. */
const dialogOf = (page: Page): Locator => page.getByRole("dialog");

/**
 * Read a set of computed properties off a locator's element, inside the page.
 *
 * One `page.evaluate` returning a typed object, asserted in Node — `scroll-area-overflow.spec.ts`'s
 * idiom, and the reason is the same: a boolean computed in the page tells you it failed, an object
 * tells you what it read.
 */
async function computed<K extends string>(
  locator: Locator,
  props: readonly K[],
): Promise<Record<K, string>> {
  return locator.evaluate((el, keys: readonly string[]) => {
    const s = getComputedStyle(el as Element);
    const out: Record<string, string> = {};
    for (const k of keys) out[k] = s.getPropertyValue(k);
    return out;
  }, props) as Promise<Record<K, string>>;
}

// ═════════════════════════════════════════════════════════════════════════════════════════════════
// (c) THE STAGE EXISTS
// ═════════════════════════════════════════════════════════════════════════════════════════════════

test.describe("CROP-01 — the crop stage renders in a real browser", () => {
  test("picking a valid photo opens the dialog and the stage is addressable by its accessible name", async ({
    page,
  }) => {
    await signUpAndReachProfile(page);
    await pick(page, "square-400.png");

    await expect(
      dialogOf(page),
      "the crop dialog did not open for `square-400.png` — a 400x400 PNG that passes all four " +
        "pre-dialog guards. Nothing below this line can be measured without it.",
    ).toBeVisible();

    // THE ONE ASSERTION JSDOM COULD NEVER MAKE. If it fails, check FIRST that the stage wrapper is
    // `position: relative` (R12): `.reactEasyCrop_Container` is `absolute; inset: 0` with no
    // intrinsic size, so an unpositioned wrapper lets the cropper escape to `DialogContent` — which
    // is `fixed` — and fill the whole overlay. That is the phase's most likely first-try bug, and
    // the box comparison in the next case is what rejects it even when the stage is "visible".
    await expect(
      stageOf(page),
      "the crop stage is not in the document. `react-easy-crop` renders the crop area only when " +
        "`state.cropSize` is truthy, which needs a non-zero container rect AND a decoded <img> — so " +
        "this failure means one of those two is missing, not that a label is wrong.",
    ).toBeVisible();
  });
});

// ═════════════════════════════════════════════════════════════════════════════════════════════════
// (d) THE BOX IS THE DERIVED ONE (Delta-2)
// ═════════════════════════════════════════════════════════════════════════════════════════════════

/**
 * Delta-2's contract is `min(320px, 100vw − 2rem, 40dvh)`, and every value below is the arithmetic
 * of THAT EXPRESSION at that viewport — not a number read off a screenshot.
 *
 * ⚠ ONE OF DELTA-2's THREE WORKED VALUES IS WRONG, AND THE BROWSER SAID SO. 16-UI-SPEC Δ2:235 prints
 * *"320 × 568 → 183px stage · 360 × 640 → 256px · 390 × 844 → 320px (capped) · desktop → 320px"*.
 * The last three are right. The first is not, and the mistake is visible in its own rationale row
 * (Δ2:232), which is where the 183 comes from: that row budgets the NON-STAGE CHROME against the
 * sheet's `max-h-[85dvh]` — *"a 640px-tall phone leaves ≈ 244px for the stage and a 568px-tall phone
 * ≈ 183px"* — and concludes that a `dvh`-relative cap is needed. 183 is the SPACE AVAILABLE that
 * motivated the `40dvh` term. It is not the value the term produces.
 *
 * Worked properly, and then MEASURED in Chromium 2026-08-25 (`boundingBox().width`):
 *
 *   | viewport   | 320px | 100vw − 2rem | 40dvh | min()  | OBSERVED   |
 *   |------------|-------|--------------|-------|--------|------------|
 *   | 320 × 568  |  320  |     288      | 227.2 | 227.2  | 227.1875   |
 *   | 360 × 640  |  320  |     328      | 256   | 256    | 256        |
 *   | 1280 × 800 |  320  |    1248      | 320   | 320    | 320        |
 *
 * The 0.0125px shortfall on the first row is Chromium's 1/64px layout grid (227.1875 = 227 + 12/64),
 * not a term being wrong. THE CONTRACT IS UNCHANGED — no class moved and no term was re-tuned; only
 * a transcription in the spec's summary line was wrong, and the plan's instruction was to record the
 * discrepancy rather than to adjust an assertion to match a surprise. The number pinned here is what
 * `min(320px, 100vw − 2rem, 40dvh)` evaluates to, which is the thing the contract actually says.
 *
 * Δ2's own reasoning survives the correction intact: 227px is still > 4× a fingertip, and the cap
 * still keeps the confirm above the fold — 227 is COMFORTABLY under the 183px of room the chrome
 * budget said was available... which is the one thing the corrected number does change, and it is
 * changed in the direction of the risk. **Flagged for the CROP-04 hardware walk (plan 16-16): on a
 * 568px-tall phone the stage is 44px TALLER than Δ2's chrome budget expected, so "does the confirm
 * button need a scroll on a small phone" is a question the walk should answer rather than assume.**
 * Δ2:994 already names the reversal — raise to `45dvh`, or drop the term — and this measurement is
 * the evidence that the term may need to move the OTHER way.
 */
const STAGE_GEOMETRY = [
  { width: 320, height: 568, expected: 227.2 },
  { width: 360, height: 640, expected: 256 },
  { width: 1280, height: 800, expected: 320 },
] as const;

/** Delta-2's terms tolerate sub-pixel layout; 1px is the band the plan pins. */
const STAGE_TOLERANCE_PX = 1;

test.describe("CROP-01 / Delta-2 — the stage measures its three derived terms", () => {
  for (const row of STAGE_GEOMETRY) {
    const where = `${row.width}x${row.height}`;

    test(`${where}: the stage is a ${row.expected}px square inside its wrapper`, async ({ page }) => {
      await page.setViewportSize({ width: row.width, height: row.height });
      await signUpAndReachProfile(page);
      await pick(page, "square-400.png");
      await expect(stageOf(page)).toBeVisible();
      await settleAnimations(page);

      const box = await wrapperOf(page).boundingBox();
      expect(box, `${where}: the stage wrapper has no layout box at all`).not.toBeNull();
      if (box === null) return;

      // IT IS A SQUARE. `size-[…]` sets both axes from one expression, so a rectangle here means
      // something else won one of them — a flex parent, or a `min-h` from the dialog body.
      expect(
        Math.abs(box.width - box.height),
        `${where}: the stage measures ${box.width}x${box.height} and is NOT square. Delta-2's box is ` +
          "one expression applied to both axes; a rectangle means a parent is stretching one of them.",
      ).toBeLessThanOrEqual(STAGE_TOLERANCE_PX);

      expect(
        Math.abs(box.width - row.expected),
        `${where}: the stage measures ${box.width}px; Delta-2's worked value is ${row.expected}px. ` +
          "The contract is `min(320px, 100vw - 2rem, 40dvh)` — a discrepancy here is either a " +
          "changed class or a term that was worked wrong, and the browser is the authority.",
      ).toBeLessThanOrEqual(STAGE_TOLERANCE_PX);

      // R12, DIRECTLY. A cropper that escaped its wrapper to `DialogContent` would still be
      // "visible" and would still be square — only this comparison rejects it.
      const dialogBox = await dialogOf(page).boundingBox();
      expect(dialogBox, `${where}: the dialog has no layout box`).not.toBeNull();
      if (dialogBox === null) return;

      expect(
        box.width,
        `${where}: the stage is ${box.width}px wide against a ${dialogBox.width}px dialog. A stage ` +
          "that is not STRICTLY narrower than its overlay has escaped its wrapper — " +
          "`.reactEasyCrop_Container` is `absolute; inset: 0` and sizes itself to the nearest " +
          "positioned ancestor, so this is what `position: relative` on the wrapper buys.",
      ).toBeLessThan(dialogBox.width);
    });
  }
});

// ═════════════════════════════════════════════════════════════════════════════════════════════════
// (e) `touch-action` IS COMPUTED `none` — AND `DialogContent` CARRIES NEITHER HALF (Delta-4)
// ═════════════════════════════════════════════════════════════════════════════════════════════════

test.describe("CROP-01 / Delta-4 — a one-finger drag on the stage cannot scroll the sheet", () => {
  test("the cropper's container computes `touch-action: none`, and the shared dialog box does not", async ({
    page,
  }) => {
    // The phone viewport, because Delta-4 is a claim about the SHEET presentation: below `sm`,
    // `SHEET_PRESENTATION` puts `max-sm:overflow-y-auto` on `DialogContent`, which is what makes the
    // guard load-bearing rather than belt-and-braces.
    await page.setViewportSize({ width: 360, height: 640 });
    await signUpAndReachProfile(page);
    await pick(page, "square-400.png");
    await expect(stageOf(page)).toBeVisible();

    // ⚠ THIS IS A VERIFICATION, NOT A RE-AUTHORING. `.reactEasyCrop_Container`'s own shipped rule
    // already sets `touch-action: none` (16-RESEARCH § A3 quotes it verbatim). What this catches is
    // the regression: somebody passing `classes.containerClassName="touch-auto"`, or a Tailwind
    // reset winning the cascade — the library injects its stylesheet UNLAYERED and Tailwind's
    // utilities are layered, so which one wins is a measurement rather than a reading.
    const container = await computed(containerOf(page), ["touch-action"]);
    expect(
      container["touch-action"],
      "the cropper's container computes `touch-action: " +
        `${container["touch-action"]}\`. With anything but \`none\` the browser starts a scroll ` +
        "gesture on the stage, the library's document-level `touchmove` never sees the drag, and a " +
        "one-finger pan scrolls the sheet out from under the photo instead of moving it (Delta-4).",
    ).toBe("none");

    // THE NEGATIVE HALF, AND IT MATTERS TO FIVE SURFACES THAT ARE NOT THIS ONE. `DialogContent` is
    // shared by six adopters; `touch-action: none` or an `overscroll-behavior` there would be a
    // regression on all of them, and the sheet must still scroll normally when the drag starts on
    // the title, the zoom row, the note or the footer. 16-RESEARCH § A3.3 says do not put either
    // there; this is the assertion that nobody did.
    const content = await computed(page.getByTestId("responsive-dialog"), [
      "touch-action",
      "overscroll-behavior-y",
    ]);
    expect(
      content["touch-action"],
      "`DialogContent` computes `touch-action: " +
        `${content["touch-action"]}\`. Delta-4's guard is scoped to the cropper's own container ON ` +
        "PURPOSE: this box is shared by six adopters, and disabling touch panning here would stop " +
        "the sheet scrolling around the stage on every one of them.",
    ).not.toBe("none");
    expect(
      content["overscroll-behavior-y"],
      "`DialogContent` computes `overscroll-behavior-y: " +
        `${content["overscroll-behavior-y"]}\`. Nothing in this phase adds an overscroll rule to ` +
        "the shared dialog box, and 16-RESEARCH § A3.3 names it as the thing not to add.",
    ).toBe("auto");
  });
});

// A GUARD ON THE HARNESS ITSELF, not on the product: every case above navigates to the dev server,
// and a suite that silently ran against nothing would report the same green as a suite that ran.
test("harness: the dev server this file measures is the one the helpers name", async ({ page }) => {
  const response = await page.goto(`${BASE}/`);
  expect(response?.status(), `${BASE} did not answer 200`).toBe(200);
});
