// CROP-01 — THE CROP STAGE, MEASURED IN A REAL BROWSER, BECAUSE THERE IS NOWHERE ELSE IT EXISTS.
//
// ═════════════════════════════════════════════════════════════════════════════════════════════════
// WHY THIS FILE EXISTS AT ALL, AND WHY A VITEST SPEC COULD NOT HAVE STOOD IN FOR IT
// ═════════════════════════════════════════════════════════════════════════════════════════════════
//
// `react-easy-crop@6.2.3` renders the crop-area element — the one carrying `tabIndex`, the
// `aria-label`, the round mask and the scrim — ONLY when `this.state.cropSize` is truthy, and
// `cropSize` is set only by `computeSizes()`, which needs a non-zero `containerRef
// .getBoundingClientRect()` AND a decoded `<img>` reporting real naturals.
//
// Probed jsdom 29.1.1 (16-RESEARCH § E) has NEITHER: `getContext("2d")` → `null`;
// `createImageBitmap`, `OffscreenCanvas`, `ResizeObserver`, `URL.createObjectURL` and
// `Image.prototype.decode` → all `undefined`; and every `getBoundingClientRect()` → zeros.
//
//   ⚠ IN JSDOM THE CROP STAGE DOES NOT EXIST IN THE DOM. Not "renders differently" — is absent.
//
// So everything geometric, gestural or pixel-bearing is Playwright or a human, and this file is the
// Playwright half's foundation. The repo has stubbed `ResizeObserver` five times and has NEVER
// stubbed `getBoundingClientRect`; two specs record in prose that they refuse to pretend jsdom has
// layout. This file is the other side of that refusal — the measurements those specs declined to
// fake, taken where they are real.
//
// ═════════════════════════════════════════════════════════════════════════════════════════════════
// TWO CONVENTIONS THIS FILE INTRODUCES, BECAUSE NOTHING IN `e2e/` HAD EITHER
// ═════════════════════════════════════════════════════════════════════════════════════════════════
//
// (1) DRIVING A FILE INPUT. `grep -rn "setInputFiles" e2e/` returned NOTHING before this file. The
//     avatar picker is the only `<input type="file">` in `src/`, it is `className="hidden"`, and it
//     is deliberately unregistered with react-hook-form. `locator.setInputFiles()` sets a hidden
//     input's `files` and dispatches `change`, which is the whole of what the shipped
//     `onAvatarChange` needs — so the bytes fed to the four guards and to the browser's own decoder
//     are the committed `e2e/fixtures/` bytes, generated by `scripts/generate-image-fixtures.mjs`
//     and gated byte-for-byte by `tests/design/image-fixtures.test.ts`. A real decoder on real
//     committed bytes is what makes the `corrupt.jpg` case honest; plan 16-10's jsdom version had to
//     mock `measureImage`, so what it proved was that the branch existed, not that it fires.
//
// (2) READING COMPUTED STYLE. `page.evaluate((el) => getComputedStyle(el)...)` answers cascade
//     questions no source scan can. The library injects its own stylesheet UNLAYERED into the
//     document head while Tailwind v4 utilities live in a cascade layer, and unlayered beats
//     layered — so "the class is in the source" and "the rule wins" are different claims here, and
//     only the second one is a behaviour. Every computed-style assertion below is a VERIFICATION of
//     a rule the library already ships, never a re-authoring of one.
//
// ═════════════════════════════════════════════════════════════════════════════════════════════════
// ⚠ THIS FILE DOES NOT DISCHARGE CROP-04. IT PRODUCES EVIDENCE FOR CROP-01.
// ═════════════════════════════════════════════════════════════════════════════════════════════════
//
// **D-175** rules that CROP-04 is discharged by a PM hardware walk on {iOS Safari, Android Chrome}
// and that planning must not claim it from a Playwright run. The mechanics agree with the decision.
// Four things this run cannot reach, named rather than waved at:
//
//   1. SAFARI'S `gesturestart` / `gesturechange` PATH. `componentDidMount` wires those up
//      separately from the two-finger touch path (16-RESEARCH § A3) — a genuinely different branch
//      of the library — and no emulator fires them. Chromium here never executes that code.
//   2. FINGER OCCLUSION of a stage that is ~227px on a 320px phone. A synthesised touch has no
//      fingertip in front of the thing being framed.
//   3. iOS MOMENTUM AND RUBBER-BANDING. `touch-action: none` asserted below is the mechanism; what
//      it feels like against a scrolling sheet on a real phone is not a computed value.
//   4. THE OS FILE PICKER — which is exactly where D-174's re-pick bug lives. `setInputFiles` sets
//      the input's value programmatically; it is not the event sequence a native picker produces.
//
// The re-pick case below therefore carries its own caveat, and the hardware walk is plan 16-16.
//
// ═════════════════════════════════════════════════════════════════════════════════════════════════
// A DEFECT ON THIS SURFACE THAT IS NOT THIS FILE'S TO FIX, AND WHAT IT COSTS THE LOCATORS
// ═════════════════════════════════════════════════════════════════════════════════════════════════
//
// The zoom slider ships with NO ACCESSIBLE NAME (`deferred-items.md` D1, measured by plan 16-10,
// assigned to plan 16-14). The element carrying `role="slider"` is Radix's THUMB; the dialog's
// `aria-label={AVATAR_ZOOM_LABEL}` lands on the Root, which renders a `<span>` with no role and so
// contributes no name to anything. `getByRole("slider", { name: "Zoom" })` matches ZERO elements
// today.
//
// So every slider locator below is `getByRole("slider")` UNNAMED, scoped to the dialog. That is
// correct-but-loose on purpose: this file does not fix the defect, does not assert that the name is
// fine, and does not encode the broken state as an expectation. ⚠ WHEN 16-14 NAMES THE THUMB, THESE
// LOCATORS SHOULD TIGHTEN TO `getByRole("slider", { name: AVATAR_ZOOM_LABEL })` — one edit per
// locator, and the scoping to `dialog` becomes redundant rather than load-bearing.
//
// ─────────────────────────────────────────────────────────────────────────────────────────────────
// SELECTORS: ZERO NEW TEST HOOKS, AND ZERO VENDOR INTERNALS (Delta-18)
// ─────────────────────────────────────────────────────────────────────────────────────────────────
//
// The stage is addressed by its accessible name, `AVATAR_POSITION_LABEL`, which is the same string a
// screen reader announces — so an assertion that passes is also evidence the stage is announceable.
//
// The library bakes two test ids of its own into its DOM — one on the crop area, one on the
// container. They are VENDOR INTERNALS that no inventory governs, and nothing here reaches for
// either. ⚠ THEY ARE DESCRIBED HERE RATHER THAN SPELLED, deliberately: this plan's acceptance
// criteria grep this file for those exact identifiers and expect zero, so a comment saying "we do
// not use them" that quoted them would be the thing that failed the check. `src/lib/avatar.ts`'s
// header and plan 16-08's rejected-decode-API paragraph set the same precedent for the same reason.
//
// The two ancestors this file needs (the library's container, and our own stage wrapper) are reached
// by walking UP from the named element, so the only string in the whole chain is one the product
// owns.

import { expect, test, type Locator, type Page } from "@playwright/test";
import { readFileSync } from "node:fs";
import path from "node:path";

import { BASE, signUpAndReachProfile } from "./helpers/avatar-session";
// The ONE definition of "a visible focus indicator" in this suite, shared with the auth walk's 59
// stops. Two copies of a focus criterion is the drift that goes silent in the worst direction.
import { expectRing, readFocus } from "./helpers/focus";
// The copy literals are IMPORTED, never re-typed (rule F2). A spec carrying its own copy of a
// sentence goes green the day the real one changes — `overflow-320.spec.ts` states the same rule for
// `SUPPORT_EMAIL`, and `src/lib/avatar.ts` is directive-free precisely so a gate can read it.
import {
  AVATAR_CROP_CANCEL,
  AVATAR_CROP_CONFIRM,
  AVATAR_CROP_CONFIRM_BUSY,
  AVATAR_CROP_TITLE,
  AVATAR_POSITION_LABEL,
  AVATAR_SOFT_SOURCE_NOTE,
  AVATAR_TOO_SMALL_MESSAGE,
  AVATAR_UNREADABLE_MESSAGE,
  AVATAR_WRONG_TYPE_MESSAGE,
} from "../src/lib/avatar";

// ═════════════════════════════════════════════════════════════════════════════════════════════════
// FIXTURES AND HANDLES
// ═════════════════════════════════════════════════════════════════════════════════════════════════

/** `<root>/e2e/fixtures` — the committed, generator-produced bytes. See `e2e/fixtures/README.md`. */
const FIXTURES = path.join(__dirname, "fixtures");

const fixture = (name: string): string => path.join(FIXTURES, name);

/**
 * Hand a fixture to the shipped picker.
 *
 * `input[type="file"]` is unambiguous by construction — `avatar-field.tsx` records that it is the
 * only one in `src/` — so Playwright's strict mode is the assertion that it stays that way.
 */
async function pick(page: Page, name: string): Promise<void> {
  await page.locator('input[type="file"]').setInputFiles(fixture(name));
}

/**
 * Wait for every running CSS animation in the document to finish before measuring anything.
 *
 * ⚠ NOT A SLEEP, AND NOT OPTIONAL — IT WAS MEASURED. `ui/dialog.tsx:73` puts
 * `data-open:animate-in data-open:zoom-in-95 duration-100` on `DialogContent`, which is a SCALE, and
 * `boundingBox()` reports the TRANSFORMED rect. Probed 2026-08-25 without this call: the 1280x800
 * stage measured **319.7356872558594px** rather than 320 — a box caught at ~99.9% of the way through
 * a 100ms zoom. It passed the 1px band by 0.26px, which is the worst possible outcome: a geometry
 * assertion whose margin is a race rather than a tolerance.
 *
 * `document.getAnimations()` returns the live CSS animations (tailwindcss-animate compiles
 * `animate-in` to a keyframe animation, not a transition), so awaiting their `finished` promises
 * waits for exactly the thing in the way and nothing else. `.catch()` swallows the rejection an
 * animation raises if it is cancelled mid-flight — a cancelled animation is a settled one for this
 * purpose.
 */
async function settleAnimations(page: Page): Promise<void> {
  await page.evaluate(() =>
    Promise.all(document.getAnimations().map((a) => a.finished.catch(() => undefined))),
  );
}

/** The crop stage: the element the library gives `tabIndex`, the round mask, and our label. */
const stageOf = (page: Page): Locator => page.getByLabel(AVATAR_POSITION_LABEL);

/**
 * The library's own container — `.reactEasyCrop_Container`, reached by walking UP from the named
 * stage rather than by its class, so no vendor string appears in a selector.
 */
const containerOf = (page: Page): Locator => stageOf(page).locator("xpath=..");

/**
 * OUR stage wrapper — the `relative … size-[min(320px,100vw-2rem,40dvh)]` box that Delta-2 derives.
 * The container above is `position: absolute; inset: 0` with no intrinsic size, so this is the
 * element that decides how big the stage is.
 */
const wrapperOf = (page: Page): Locator => stageOf(page).locator("xpath=../..");

/** Either overlay, addressed by role. `data-testid="responsive-dialog"` is the pattern's own. */
const dialogOf = (page: Page): Locator => page.getByRole("dialog");

/**
 * The field's refusal region when it sits ON THE PAGE — no file staged, no overlay open.
 *
 * ⚠ SCOPED TO `main`, AND THE SCOPE IS NOT TIDINESS. A bare `page.getByRole("alert")` matches TWO
 * elements on this route and fails Playwright's strict mode. MEASURED 2026-08-25: the second is an
 * empty `<div role="alert">` inside `<next-route-announcer>`'s SHADOW ROOT — Next's own route
 * announcer, which `getByRole` reaches because Playwright's role engine pierces open shadow roots.
 * It is framework furniture, it ships in production as well as dev, no visitor can address it, and it
 * is permanently empty. `helpers/focus.ts`'s `DEV_OVERLAY_TAG` is the same situation with the same
 * shape of answer.
 *
 * ⚠ AND THE PARTITION IS ASSERTED, NOT TRUSTED — see `expectNoStrayAlerts`. A scope that silently
 * swallowed a SECOND product alert would hide exactly the defect `avatar-field.tsx`'s "one refusal
 * slot" docblock and `src/lib/design/live-regions.ts` exist to prevent.
 */
const pageAlertOf = (page: Page): Locator => page.getByRole("main").getByRole("alert");

// The field's refusal region has a SECOND placement — inside whichever overlay is open — and this
// file deliberately declares no handle for it. The in-dialog half is the save-failure sentence (rule
// F5: the dialog stays open with the framing intact), and asserting it needs a save that FAILS on
// demand; the pending-window case below makes a save succeed on demand, which is the opposite
// instrument. `tests/profile/avatar-field.test.tsx` already covers the failure sentence in jsdom,
// where the state can be driven directly and no cropper is needed to reach it. The absence is a
// division of labour, not a gap.

/** The zoom row's control. UNNAMED on purpose — see the header's note on deferred item D1. */
const sliderOf = (page: Page): Locator => dialogOf(page).getByRole("slider");

/**
 * Every `role="alert"` this document holds that is NOT the product's must be Next's route announcer.
 *
 * This is the assertion that makes `pageAlertOf`'s scope honest rather than convenient: it names the
 * one element the scope drops and fails if anything else appears, so the day a second product alert
 * is added the scope reports it instead of hiding it.
 */
async function expectNoStrayAlerts(page: Page, where: string): Promise<void> {
  const strays = await page.getByRole("alert").evaluateAll((nodes) =>
    nodes
      .filter((n) => n.closest("main") === null && n.closest('[role="dialog"]') === null)
      .map((n) => {
        const root = n.getRootNode();
        const host = root instanceof ShadowRoot ? root.host.tagName : null;
        return `${host ?? "(light DOM)"}>${n.tagName}:"${(n.textContent ?? "").trim().slice(0, 40)}"`;
      }),
  );
  expect(
    strays,
    `${where}: an interrupting region outside \`main\` and outside every dialog. The ONLY one this ` +
      "suite tolerates is Next's own empty route announcer; anything else is a live region the " +
      "product added where `live-regions.ts` has not declared it.",
  ).toEqual(['NEXT-ROUTE-ANNOUNCER>DIV:""']);
}

/**
 * Read a set of computed properties off a locator's element, inside the page.
 *
 * One `page.evaluate` returning a typed object, asserted in Node — `scroll-area-overflow.spec.ts`'s
 * idiom, and the reason is the same: a boolean computed in the page tells you it failed, an object
 * tells you what it read.
 */
async function computed<K extends string>(
  locator: Locator,
  props: readonly K[],
): Promise<Record<K, string>> {
  return locator.evaluate((el, keys: readonly string[]) => {
    const s = getComputedStyle(el as Element);
    const out: Record<string, string> = {};
    for (const k of keys) out[k] = s.getPropertyValue(k);
    return out;
  }, props) as Promise<Record<K, string>>;
}

// ═════════════════════════════════════════════════════════════════════════════════════════════════
// (c) THE STAGE EXISTS
// ═════════════════════════════════════════════════════════════════════════════════════════════════

test.describe("CROP-01 — the crop stage renders in a real browser", () => {
  test("picking a valid photo opens the dialog and the stage is addressable by its accessible name", async ({
    page,
  }) => {
    await signUpAndReachProfile(page);
    await pick(page, "square-400.png");

    await expect(
      dialogOf(page),
      "the crop dialog did not open for `square-400.png` — a 400x400 PNG that passes all four " +
        "pre-dialog guards. Nothing below this line can be measured without it.",
    ).toBeVisible();

    // THE ONE ASSERTION JSDOM COULD NEVER MAKE. If it fails, check FIRST that the stage wrapper is
    // `position: relative` (R12): `.reactEasyCrop_Container` is `absolute; inset: 0` with no
    // intrinsic size, so an unpositioned wrapper lets the cropper escape to `DialogContent` — which
    // is `fixed` — and fill the whole overlay. That is the phase's most likely first-try bug, and
    // the box comparison in the next case is what rejects it even when the stage is "visible".
    await expect(
      stageOf(page),
      "the crop stage is not in the document. `react-easy-crop` renders the crop area only when " +
        "`state.cropSize` is truthy, which needs a non-zero container rect AND a decoded <img> — so " +
        "this failure means one of those two is missing, not that a label is wrong.",
    ).toBeVisible();
  });
});

// ═════════════════════════════════════════════════════════════════════════════════════════════════
// (d) THE BOX IS THE DERIVED ONE (Delta-2)
// ═════════════════════════════════════════════════════════════════════════════════════════════════

/**
 * Delta-2's contract is `min(320px, 100vw − 2rem, 40dvh)`, and every value below is the arithmetic
 * of THAT EXPRESSION at that viewport — not a number read off a screenshot.
 *
 * ⚠ ONE OF DELTA-2's THREE WORKED VALUES IS WRONG, AND THE BROWSER SAID SO. 16-UI-SPEC Δ2:235 prints
 * *"320 × 568 → 183px stage · 360 × 640 → 256px · 390 × 844 → 320px (capped) · desktop → 320px"*.
 * The last three are right. The first is not, and the mistake is visible in its own rationale row
 * (Δ2:232), which is where the 183 comes from: that row budgets the NON-STAGE CHROME against the
 * sheet's `max-h-[85dvh]` — *"a 640px-tall phone leaves ≈ 244px for the stage and a 568px-tall phone
 * ≈ 183px"* — and concludes that a `dvh`-relative cap is needed. 183 is the SPACE AVAILABLE that
 * motivated the `40dvh` term. It is not the value the term produces.
 *
 * Worked properly, and then MEASURED in Chromium 2026-08-25 (`boundingBox().width`):
 *
 *   | viewport   | 320px | 100vw − 2rem | 40dvh | min()  | OBSERVED   |
 *   |------------|-------|--------------|-------|--------|------------|
 *   | 320 × 568  |  320  |     288      | 227.2 | 227.2  | 227.1875   |
 *   | 360 × 640  |  320  |     328      | 256   | 256    | 256        |
 *   | 1280 × 800 |  320  |    1248      | 320   | 320    | 320        |
 *
 * The 0.0125px shortfall on the first row is Chromium's 1/64px layout grid (227.1875 = 227 + 12/64),
 * not a term being wrong. THE CONTRACT IS UNCHANGED — no class moved and no term was re-tuned; only
 * a transcription in the spec's summary line was wrong, and the plan's instruction was to record the
 * discrepancy rather than to adjust an assertion to match a surprise. The number pinned here is what
 * `min(320px, 100vw − 2rem, 40dvh)` evaluates to, which is the thing the contract actually says.
 *
 * Δ2's own reasoning survives the correction intact: 227px is still > 4× a fingertip, and the cap
 * still keeps the confirm above the fold — 227 is COMFORTABLY under the 183px of room the chrome
 * budget said was available... which is the one thing the corrected number does change, and it is
 * changed in the direction of the risk. **Flagged for the CROP-04 hardware walk (plan 16-16): on a
 * 568px-tall phone the stage is 44px TALLER than Δ2's chrome budget expected, so "does the confirm
 * button need a scroll on a small phone" is a question the walk should answer rather than assume.**
 * Δ2:994 already names the reversal — raise to `45dvh`, or drop the term — and this measurement is
 * the evidence that the term may need to move the OTHER way.
 */
const STAGE_GEOMETRY = [
  { width: 320, height: 568, expected: 227.2 },
  { width: 360, height: 640, expected: 256 },
  { width: 1280, height: 800, expected: 320 },
] as const;

/** Delta-2's terms tolerate sub-pixel layout; 1px is the band the plan pins. */
const STAGE_TOLERANCE_PX = 1;

test.describe("CROP-01 / Delta-2 — the stage measures its three derived terms", () => {
  for (const row of STAGE_GEOMETRY) {
    const where = `${row.width}x${row.height}`;

    test(`${where}: the stage is a ${row.expected}px square inside its wrapper`, async ({ page }) => {
      await page.setViewportSize({ width: row.width, height: row.height });
      await signUpAndReachProfile(page);
      await pick(page, "square-400.png");
      await expect(stageOf(page)).toBeVisible();
      await settleAnimations(page);

      const box = await wrapperOf(page).boundingBox();
      expect(box, `${where}: the stage wrapper has no layout box at all`).not.toBeNull();
      if (box === null) return;

      // IT IS A SQUARE. `size-[…]` sets both axes from one expression, so a rectangle here means
      // something else won one of them — a flex parent, or a `min-h` from the dialog body.
      expect(
        Math.abs(box.width - box.height),
        `${where}: the stage measures ${box.width}x${box.height} and is NOT square. Delta-2's box is ` +
          "one expression applied to both axes; a rectangle means a parent is stretching one of them.",
      ).toBeLessThanOrEqual(STAGE_TOLERANCE_PX);

      expect(
        Math.abs(box.width - row.expected),
        `${where}: the stage measures ${box.width}px; Delta-2's worked value is ${row.expected}px. ` +
          "The contract is `min(320px, 100vw - 2rem, 40dvh)` — a discrepancy here is either a " +
          "changed class or a term that was worked wrong, and the browser is the authority.",
      ).toBeLessThanOrEqual(STAGE_TOLERANCE_PX);

      // R12, DIRECTLY. A cropper that escaped its wrapper to `DialogContent` would still be
      // "visible" and would still be square — only this comparison rejects it.
      const dialogBox = await dialogOf(page).boundingBox();
      expect(dialogBox, `${where}: the dialog has no layout box`).not.toBeNull();
      if (dialogBox === null) return;

      expect(
        box.width,
        `${where}: the stage is ${box.width}px wide against a ${dialogBox.width}px dialog. A stage ` +
          "that is not STRICTLY narrower than its overlay has escaped its wrapper — " +
          "`.reactEasyCrop_Container` is `absolute; inset: 0` and sizes itself to the nearest " +
          "positioned ancestor, so this is what `position: relative` on the wrapper buys.",
      ).toBeLessThan(dialogBox.width);
    });
  }
});

// ═════════════════════════════════════════════════════════════════════════════════════════════════
// (e) `touch-action` IS COMPUTED `none` — AND `DialogContent` CARRIES NEITHER HALF (Delta-4)
// ═════════════════════════════════════════════════════════════════════════════════════════════════

test.describe("CROP-01 / Delta-4 — a one-finger drag on the stage cannot scroll the sheet", () => {
  test("the cropper's container computes `touch-action: none`, and the shared dialog box does not", async ({
    page,
  }) => {
    // The phone viewport, because Delta-4 is a claim about the SHEET presentation: below `sm`,
    // `SHEET_PRESENTATION` puts `max-sm:overflow-y-auto` on `DialogContent`, which is what makes the
    // guard load-bearing rather than belt-and-braces.
    await page.setViewportSize({ width: 360, height: 640 });
    await signUpAndReachProfile(page);
    await pick(page, "square-400.png");
    await expect(stageOf(page)).toBeVisible();

    // ⚠ THIS IS A VERIFICATION, NOT A RE-AUTHORING. `.reactEasyCrop_Container`'s own shipped rule
    // already sets `touch-action: none` (16-RESEARCH § A3 quotes it verbatim). What this catches is
    // the regression: somebody passing `classes.containerClassName="touch-auto"`, or a Tailwind
    // reset winning the cascade — the library injects its stylesheet UNLAYERED and Tailwind's
    // utilities are layered, so which one wins is a measurement rather than a reading.
    const container = await computed(containerOf(page), ["touch-action"]);
    expect(
      container["touch-action"],
      "the cropper's container computes `touch-action: " +
        `${container["touch-action"]}\`. With anything but \`none\` the browser starts a scroll ` +
        "gesture on the stage, the library's document-level `touchmove` never sees the drag, and a " +
        "one-finger pan scrolls the sheet out from under the photo instead of moving it (Delta-4).",
    ).toBe("none");

    // THE NEGATIVE HALF, AND IT MATTERS TO FIVE SURFACES THAT ARE NOT THIS ONE. `DialogContent` is
    // shared by six adopters; `touch-action: none` or an `overscroll-behavior` there would be a
    // regression on all of them, and the sheet must still scroll normally when the drag starts on
    // the title, the zoom row, the note or the footer. 16-RESEARCH § A3.3 says do not put either
    // there; this is the assertion that nobody did.
    const content = await computed(page.getByTestId("responsive-dialog"), [
      "touch-action",
      "overscroll-behavior-y",
    ]);
    expect(
      content["touch-action"],
      "`DialogContent` computes `touch-action: " +
        `${content["touch-action"]}\`. Delta-4's guard is scoped to the cropper's own container ON ` +
        "PURPOSE: this box is shared by six adopters, and disabling touch panning here would stop " +
        "the sheet scrolling around the stage on every one of them.",
    ).not.toBe("none");
    expect(
      content["overscroll-behavior-y"],
      "`DialogContent` computes `overscroll-behavior-y: " +
        `${content["overscroll-behavior-y"]}\`. Nothing in this phase adds an overscroll rule to ` +
        "the shared dialog box, and 16-RESEARCH § A3.3 names it as the thing not to add.",
    ).toBe("auto");
  });
});

// ═════════════════════════════════════════════════════════════════════════════════════════════════
// (a) THE FOUR PRE-DIALOG REFUSALS — WITH A REAL DECODER ON REAL BYTES
// ═════════════════════════════════════════════════════════════════════════════════════════════════
//
// 999.2 § 2e's fixed order is type → size → decode → dimensions, and three of the four are asserted
// here (the size guard needs a >5MB file, which no fixture is and which the server re-checks anyway).
//
// WHAT MAKES THESE DIFFERENT FROM PLAN 16-10's JSDOM VERSIONS. There, `measureImage` was MOCKED —
// jsdom has no decoder — so what those cases proved is that the branch exists and renders its
// sentence when told to. Here Chromium decodes the committed bytes itself, so the branch is reached
// by the decoder's own verdict. `corrupt.jpg` is the case that could not have been written honestly
// anywhere else: it needs a decoder that actually fails, and getting one to fail took plan 16-04 five
// measured attempts (a truncated entropy-coded scan fires `load` at every depth; only a cut inside
// the Huffman-table segment fires `error`).

const REFUSALS = [
  {
    fixture: "tiny.gif",
    expected: AVATAR_WRONG_TYPE_MESSAGE,
    guard: "1 · TYPE — `image/gif` is outside AVATAR_ALLOWED_TYPES",
  },
  {
    fixture: "tiny.svg",
    expected: AVATAR_WRONG_TYPE_MESSAGE,
    // The one rejection that matters beyond tidiness: an SVG is a scriptable document, not an image.
    guard: "1 · TYPE — `image/svg+xml`, a scriptable document",
  },
  {
    fixture: "corrupt.jpg",
    expected: AVATAR_UNREADABLE_MESSAGE,
    guard: "3 · DECODE — a plausible JPEG header cut inside its Huffman tables",
  },
  {
    fixture: "tiny-150.png",
    expected: AVATAR_TOO_SMALL_MESSAGE,
    guard: "4 · DIMENSIONS — 150px shorter side, below AVATAR_MIN_SOURCE_PX",
  },
] as const;

test.describe("CROP-01 / 999.2 § 2e — the four pre-dialog refusals, decoded for real", () => {
  for (const row of REFUSALS) {
    test(`${row.fixture} is refused before the dialog (guard ${row.guard})`, async ({ page }) => {
      await signUpAndReachProfile(page);
      await pick(page, row.fixture);

      await expect(
        pageAlertOf(page),
        `${row.fixture}: the refusal region does not carry the sentence guard ${row.guard} owns. ` +
          "The literal is imported from `@/lib/avatar`, so this is a disagreement about BEHAVIOUR " +
          "and never about spelling.",
      ).toHaveText(row.expected);

      // BOTH HALVES, ALWAYS. A refusal that also opened the dialog would put a person in a framing
      // step for a file the app has already declined — and the sentence alone cannot tell you that
      // did not happen.
      await expect(
        dialogOf(page),
        `${row.fixture}: a dialog is mounted after a refusal. Guard ${row.guard} must return BEFORE ` +
          "`setStaged`, and the dialog is mounted only while a file is staged.",
      ).toHaveCount(0);

      // Exactly one interrupting region, and it is the field's own. `live-regions.ts` declares ONE
      // alert for `avatar-field.tsx`; a second would be an undeclared `alert#2`.
      await expect(
        pageAlertOf(page),
        `${row.fixture}: more than one product alert is mounted at once`,
      ).toHaveCount(1);
      await expectNoStrayAlerts(page, row.fixture);
    });
  }
});

// ═════════════════════════════════════════════════════════════════════════════════════════════════
// (b) THE ZOOM ROW — DISABLED WITH ITS REASON, AND BOTH OF THOSE ARE CONDITIONAL
// ═════════════════════════════════════════════════════════════════════════════════════════════════
//
// ⚠ A CORRECTION TO THIS PLAN'S OWN EXPECTATION, MEASURED AND THEN CHECKED AGAINST THE CONTRACT.
//
// `16-13-PLAN.md` (b) and `e2e/fixtures/README.md`'s `square-400.png` row both say that at a 400px
// source the zoom row is disabled and `AVATAR_SOFT_SOURCE_NOTE` is **NOT** rendered — *"400 is
// neither below `AVATAR_MIN_SOURCE_PX` nor under 400"* — and the plan's reason for wanting that case
// is to prove the note is conditional rather than always-on.
//
// MEASURED 2026-08-25: at `square-400.png` the note **IS** rendered. And the shipped code is right,
// because the settled contract says so in its own worked table:
//
//   `tests/design/avatar-zoom.test.ts:96` — IC-05's 400x400 row, verbatim:
//       "IC-05 · 400 x 400 — zoom row disabled + soft note"
//
// IC-05 is 999.2's, inherited by D-176 and explicitly NOT to be re-derived. `image-crop-dialog.tsx`
// gates the note on `zoomLocked` (`maxZoom <= 1`), which is true at exactly 400 — matching IC-05.
// The plan text and the fixture README are the two documents that re-derived the boundary as
// exclusive and disagreed with the table they inherited. The code and IC-05 agree; two later
// paraphrases do not. **The paraphrases are what is wrong, and this spec follows the contract.**
//
// THE PLAN'S INTENT IS STILL DISCHARGED, AND MORE STRONGLY, by a third row it did not ask for:
// `panorama-4000x500.jpg` has a 500px shorter side, so `avatarMaxZoom(500)` is 1.25, the row is
// ENABLED and the note is ABSENT. That proves BOTH the disabled state and the note are conditional —
// where the 400px case would only ever have proved one of them, and would have proved it wrong.
//
// ONE THING WORTH THE PM'S TIME, LOGGED RATHER THAN FIXED HERE: at exactly 400 the sentence the row
// carries reads *"This photo is small, so it may look a little soft"*, and a 400px source is
// pixel-for-pixel the output size — nothing about it is soft. Rule F8 wants a disabled control to
// carry ITS REASON, and at 400 the real reason is "there is no zoom headroom", not softness. That is
// a COPY decision, not an executor's, and product code is frozen for this plan. Filed as D3 in
// `deferred-items.md`.

const ZOOM_ROWS = [
  {
    fixture: "square-400.png",
    shorter: 400,
    locked: true,
    note: true,
    why: "avatarMaxZoom(400) === 1 — no headroom (IC-05's own 400x400 row)",
  },
  {
    fixture: "small-300.png",
    shorter: 300,
    locked: true,
    note: true,
    why: "avatarMaxZoom(300) === 1 — inside D-173's [200, 400) soft band",
  },
  {
    fixture: "panorama-4000x500.jpg",
    shorter: 500,
    locked: false,
    note: false,
    why: "avatarMaxZoom(500) === 1.25 — real headroom, so neither half applies",
  },
] as const;

test.describe("CROP-01 / rule F8 — the zoom row is disabled with its reason, conditionally", () => {
  for (const row of ZOOM_ROWS) {
    const state = row.locked ? "DISABLED" : "enabled";

    test(`${row.fixture} (shorter ${row.shorter}px): the row is ${state} — ${row.why}`, async ({
      page,
    }) => {
      await signUpAndReachProfile(page);
      await pick(page, row.fixture);
      await expect(stageOf(page)).toBeVisible();

      const slider = sliderOf(page);
      await expect(
        slider,
        `${row.fixture}: the zoom control is not rendered. Rule F8 disables it, never hides it — a ` +
          "control that vanishes teaches nothing.",
      ).toHaveCount(1);

      // ⚠ `data-disabled`, NOT `toBeDisabled()`. MEASURED: Radix's thumb is a `<span role="slider">`
      // that carries `data-disabled=""` and drops out of the tab order, but exposes NO
      // `aria-disabled` — which is what `toBeDisabled()` reads on a non-native control, so it would
      // report every state as enabled. That missing `aria-disabled` is the same family of defect as
      // D1 (the thumb has no accessible name either) and belongs to plan 16-14 with it; this file
      // asserts the mechanism that IS shipped rather than the one that should be.
      const disabledAttr = await slider.getAttribute("data-disabled");
      const tabindex = await slider.getAttribute("tabindex");

      if (row.locked) {
        expect(
          disabledAttr,
          `${row.fixture}: the zoom row is live at a source with no headroom. ${row.why}.`,
        ).not.toBeNull();
        // The behavioural half of "disabled": it is not a keyboard stop.
        expect(
          tabindex,
          `${row.fixture}: the disabled zoom thumb is still in the tab order (tabindex=${tabindex}).`,
        ).toBeNull();
      } else {
        expect(
          disabledAttr,
          `${row.fixture}: the zoom row is disabled at a source with real headroom. ${row.why}.`,
        ).toBeNull();
        expect(
          tabindex,
          `${row.fixture}: the live zoom thumb is not a keyboard stop.`,
        ).toBe("0");
        // Non-vacuity: the ceiling really did arrive from the image, not from the initial state.
        await expect(
          slider,
          `${row.fixture}: the slider's ceiling is still the mount-time 1. The per-image bound comes ` +
            "from `onMediaLoaded`, so a stuck 1 means the media size never reached the component.",
        ).toHaveAttribute("aria-valuemax", "1.25");
      }

      const note = dialogOf(page).getByText(AVATAR_SOFT_SOURCE_NOTE);
      await expect(
        note,
        row.note
          ? `${row.fixture}: the zoom row is disabled and carries NO reason. Rule F8 — a disabled ` +
            "control always says why."
          : `${row.fixture}: the soft-source note is rendered beside a LIVE zoom row. It is ` +
            "conditional on the row being locked, not decoration.",
      ).toHaveCount(row.note ? 1 : 0);
    });
  }
});

// ═════════════════════════════════════════════════════════════════════════════════════════════════
// (c) D-174 — CANCEL, THEN RE-PICK THE IDENTICAL FILE
// ═════════════════════════════════════════════════════════════════════════════════════════════════

test.describe("CROP-01 / D-174 — the same file, picked twice, opens the cropper twice", () => {
  test("cancelling and re-choosing the identical file re-opens the dialog", async ({ page }) => {
    await signUpAndReachProfile(page);

    await pick(page, "square-400.png");
    await expect(stageOf(page), "the first pick did not open the cropper").toBeVisible();

    await dialogOf(page).getByRole("button", { name: AVATAR_CROP_CANCEL, exact: true }).click();
    await expect(
      dialogOf(page),
      "Cancel did not close the cropper. A cancel is structurally a no-op — the dialog is mounted " +
        "only while a file is staged, so unstaging IS unmounting.",
    ).toHaveCount(0);

    // THE SAME PATH, BYTE-FOR-BYTE. Without `e.target.value = ""` in the change handler's `finally`,
    // the browser fires no `change` event for a file identical to the one already in the input, and
    // the flow dies in complete silence — no dialog, no refusal, no sign anything was asked. That is
    // the shipped bug D-174 makes an acceptance criterion.
    await pick(page, "square-400.png");
    await expect(
      stageOf(page),
      "re-picking the identical file did nothing. The file input's `value` was not reset after the " +
        "first handled change (D-174), so the browser had no `change` event to fire.",
    ).toBeVisible();

    // ⚠ THE HONEST LIMIT OF THIS CASE, STATED WHERE IT IS MADE. `setInputFiles` assigns the input's
    // `files` programmatically and dispatches `change`; that is NOT byte-for-byte the event sequence
    // a native OS picker produces, and the OS picker is exactly where D-174's bug lives. So this is
    // EVIDENCE THAT THE RESET EXISTS AND WORKS, and it is NOT the discharge of D-174's clause in
    // CROP-04. **Plan 16-16's hardware walk is.** (D-175.)
  });
});

// ═════════════════════════════════════════════════════════════════════════════════════════════════
// (d) DELTA-3 — ONE GUARD, THREE AFFORDANCES, PROVEN INERT MID-SAVE
// ═════════════════════════════════════════════════════════════════════════════════════════════════
//
// This is the part jsdom could not assert at all, for the reason the whole file exists: without the
// stage there is no confirm to press that produces a Blob.
//
// HOW THE PENDING WINDOW IS MADE REAL, AND WHY IT IS AN INTERCEPTION RATHER THAN A BIG FILE. A
// fixture large enough to make the upload "slow" is a race dressed as a test — it would pass on a
// fast link and hang on a slow one, and it could never assert that the window CLOSED on success.
// Holding the request open makes the window arbitrarily long and closes it on command.
//
// THE REQUEST IS MATCHED BY HEADER, NEVER BY PATH. A Next server action POSTs to the CURRENT ROUTE
// URL, so a path filter matches the navigation or nothing at all; `next-action` is the observed
// header name, recorded in `e2e/public-listing.spec.ts`'s header and used the same way by
// `e2e/mobile-booker-path.spec.ts:570-578`.
//
// ⚠ THIS CASE PERFORMS ONE REAL UPLOAD, AND THAT IS A DELIBERATE COST. When the gate opens the
// request is `continue()`d to the real action, which really uploads a 400x400 JPEG to Cloudinary
// under `fitout/avatars/<the throwaway signup's user id>` — because "the dialog closes ON SUCCESS"
// is not a claim a fabricated response can support, and hand-rolling a Next flight payload would be
// asserting against our own forgery. The asset is orphaned the moment the test ends: nothing ever
// reads that user's row again. D-169 already tolerates orphans knowingly and Phase 16.1's audit
// sweeps them; this run adds one per execution, and that is logged as D4 in `deferred-items.md` so
// the sweep knows to expect an `e2e.avatar.*` cohort.

test.describe("CROP-01 / Delta-3 — one guard makes all three dismiss affordances inert", () => {
  test("Escape, the overlay click and the close control all do nothing while a save is in flight", async ({
    page,
  }) => {
    await signUpAndReachProfile(page);

    let release!: () => void;
    const gate = new Promise<void>((resolve) => {
      release = resolve;
    });
    let heldActions = 0;

    await page.route("**/*", async (route) => {
      const request = route.request();
      if (request.method() === "POST" && request.headers()["next-action"] !== undefined) {
        heldActions += 1;
        await gate;
      }
      await route.continue();
    });

    await pick(page, "square-400.png");
    await expect(stageOf(page)).toBeVisible();

    const dialog = dialogOf(page);
    const confirm = dialog.getByRole("button", { name: AVATAR_CROP_CONFIRM, exact: true });
    await confirm.click();

    // THE WINDOW IS REAL BEFORE ANYTHING IS ASSERTED ABOUT IT. A guard test whose pending state
    // never began would find the dialog open for the trivial reason that nothing had happened —
    // vacuous, and green. The busy label is the component's own statement that it is saving.
    const busy = dialog.getByRole("button", { name: AVATAR_CROP_CONFIRM_BUSY, exact: true });
    await expect(
      busy,
      "the confirm never reached its busy label, so there is no pending window to test. Either the " +
        "action request was not intercepted or the encode failed before it was issued.",
    ).toBeVisible();

    // Delta-3's SECOND visible busy signal, and the one affordance that is disabled rather than
    // merely inert: `Cancel`. (The close control carries neither, which is the recorded cost.)
    await expect(
      dialog.getByRole("button", { name: AVATAR_CROP_CANCEL, exact: true }),
      "`Cancel` is live during a save. It is the one dismiss affordance that CAN carry a disabled " +
        "state, and Delta-3 says it does.",
    ).toBeDisabled();

    // ⚠ `expect.soft`, AND THE REASON IS THE CLAIM ITSELF. Delta-3's assertion is not "three things
    // are inert" — it is "ONE line makes three things inert". A hard assertion would stop at the
    // first affordance, and a report naming only Escape would understate the defect to exactly the
    // reader who needs to see that the three move together. Soft assertions still fail the test;
    // they just let all three speak. (Watched red, transcribed at the bottom of this block.)
    const stillOpen = async (affordance: string): Promise<void> => {
      await expect
        .soft(
          dialog.getByRole("heading", { name: AVATAR_CROP_TITLE, exact: true }),
          `${affordance} closed the crop dialog during a save. Radix routes Escape, the overlay ` +
            "click AND the close control through ONE `onOpenChange`, so `if (!next && saving) " +
            "return;` is the single line that makes all three inert — if this failed, expect the " +
            "other two to have failed with it.",
        )
        .toBeVisible({ timeout: 5_000 });
    };

    // 1. ESCAPE.
    await page.keyboard.press("Escape");
    await stillOpen("Escape");

    // 2. THE OVERLAY, CLICKED OUTSIDE THE PANEL. `page.mouse` rather than a locator click: the
    //    overlay sits under the content, so an actionability-checked click on it is a fight with
    //    the panel rather than a click outside it. (5, 5) is the top-left corner of the default
    //    1280x720 viewport, which no centred `sm:max-w-sm` panel reaches.
    await page.mouse.click(5, 5);
    await stillOpen("the overlay click");

    // 3. THE CLOSE CONTROL. Named `Close` by the vendored `DialogContent`'s own `sr-only` span; the
    //    pattern deliberately does not rename it here, because exactly one of this phase's two
    //    overlays is mounted at any instant. The short explicit timeout is for the RED case: with
    //    the guard removed the control is already gone, and a 30s wait for a button that a previous
    //    affordance dismissed is a worse report than a fast one.
    await dialog
      .getByRole("button", { name: "Close", exact: true })
      .click({ timeout: 5_000 });
    await stillOpen("the close control");

    // AND THEN IT CLOSES ON SUCCESS — which is what separates "inert while saving" from "broken".
    release();
    await expect(
      dialog,
      "the crop dialog did not close after the save completed. The guard is `!next && saving`, so it " +
        "must stop guarding the moment `saving` goes false.",
    ).toHaveCount(0, { timeout: 30_000 });

    expect(
      heldActions,
      "no server action request was ever intercepted, so the pending window above was not the one " +
        "this test thinks it was measuring.",
    ).toBeGreaterThan(0);

    // The round trip really happened: the circle now renders the stored avatar rather than initials.
    await expect(
      page.getByRole("main").locator('img[alt="Your avatar"]'),
      "the avatar circle still shows initials after a successful save.",
    ).toBeVisible({ timeout: 30_000 });
  });
});

// ═════════════════════════════════════════════════════════════════════════════════════════════════
// TASK 3 — THE KEYBOARD PAN IS THE LIBRARY'S, AND THE FOCUS INDICATOR IS OURS (D-178)
// ═════════════════════════════════════════════════════════════════════════════════════════════════
//
// D-178 is a PM ruling that AMENDS settled contract text, and these cases are what make it
// verifiable rather than merely written down. 999.2 § 2g asked for a hand-rolled `onKeyDown` mapping
// the arrows to 8px and Shift to a 24px COARSE adjust, on the stated belief that
// *"`react-easy-crop` does not provide this"*. In 6.2.3 it does: the crop area already ships
// `tabIndex={0}`, arrow-key panning, `restrictPosition` clamping and `emitCropData` re-pairing — and
// its Shift is `step *= 0.2`, a FINE adjust, the opposite direction from § 2g's.
//
// **D-178 accepts what ships.** The accessibility requirement is met either way (the stage is
// focusable and pannable without a pointer); only the modifier's direction changed. The cost of
// matching § 2g's letter would be a custom handler that discards the clamp and the re-emit — the
// cross-browser bug class D-167 chose a library to avoid.

/** The `translate(Xpx, Ypx)` the library writes onto its own `<img>`, in container pixels. */
type CropOffset = { readonly x: number; readonly y: number };

/**
 * Read the crop position off the media element's inline transform.
 *
 * THE MEDIA ELEMENT IS REACHED THROUGH THE NAMED STAGE, never by the library's class: the crop area
 * and the `<img>` are siblings inside the container, so `parentElement.querySelector("img")` walks
 * one step up and one across. The library writes
 * `translate(${crop.x}px, ${crop.y}px) rotate(0deg) scale(${zoom})` on every render, so this string
 * IS the component's crop state — not a proxy for it, and not a re-derivation this spec could get
 * wrong independently.
 */
async function readCropOffset(page: Page): Promise<CropOffset> {
  const transform = await stageOf(page).evaluate((el) => {
    const img = el.parentElement?.querySelector("img");
    return img instanceof HTMLImageElement ? img.style.transform : "";
  });
  const match = /translate\((-?[\d.]+)px,\s*(-?[\d.]+)px\)/.exec(transform);
  expect(
    match,
    `the cropper's media element carries no parsable translate — read "${transform}". The library ` +
      "writes the crop position into this transform on every render, so an unparsable one means the " +
      "element found is not the media element.",
  ).not.toBeNull();
  return { x: Number(match?.[1] ?? NaN), y: Number(match?.[2] ?? NaN) };
}

/**
 * Tab until the crop stage has focus, and fail with the order it walked if it never does.
 *
 * ⚠ REAL KEY PRESSES, NEVER `.focus()`. `helpers/focus.ts` records the measurement: a programmatic
 * focus does not match `:focus-visible` in Chromium, so a version of this that called `.focus()`
 * would report the stage as drawing nothing and would be red on a correct tree.
 *
 * MEASURED ORDER inside the crop dialog with a LIVE zoom row (2026-08-25): the stage holds focus at
 * open (it is the first tabbable in `DialogContent`), then slider thumb → `Cancel` → `Save photo` →
 * `Close` → back to the stage. Five presses. With the row DISABLED the thumb leaves the order and it
 * is four. The bound below is triple the longer of the two, which is `WALK_BOUND`'s reasoning at a
 * smaller scale: an unbounded loop inside a focus trap is a hang, and a hang is a worse report than
 * an assertion.
 */
const STAGE_TAB_BOUND = 15;

async function tabToStage(page: Page): Promise<string[]> {
  const walked: string[] = [];
  for (let i = 0; i < STAGE_TAB_BOUND; i += 1) {
    await page.keyboard.press("Tab");
    const stop = await page.evaluate(() => {
      const el = document.activeElement;
      if (!(el instanceof HTMLElement)) return "(nothing)";
      const name = el.getAttribute("aria-label") ?? (el.textContent ?? "").trim();
      return `${el.tagName.toLowerCase()}[${el.getAttribute("role") ?? ""}]:${name.slice(0, 30)}`;
    });
    walked.push(stop);
    if (stop.includes(AVATAR_POSITION_LABEL.slice(0, 14))) return walked;
  }
  expect(
    walked,
    `the crop stage never took focus in ${STAGE_TAB_BOUND} Tab presses. It is the crop-area element ` +
      "the library renders with `tabIndex={0}`, so this means either the element is absent (no " +
      "`cropSize`) or something removed it from the tab order.",
  ).toEqual([]);
  return walked;
}

/**
 * The two axis fixtures, and what each proves about the OTHER one.
 *
 * A panorama alone cannot distinguish "the vertical axis is clamped" from "the vertical key does
 * nothing" — the reading is identical. Running the same two keys against the AXIS-SWAPPED fixture is
 * what separates them: the key that is pinned on one is the key that pans on the other. That is the
 * repo's own rule about vacuity applied to a clamp — the tell is runtime, not output.
 */
const AXIS_FIXTURES = [
  {
    fixture: "panorama-4000x500.jpg",
    pans: { key: "ArrowLeft", axis: "x" },
    pinned: { key: "ArrowUp", axis: "y" },
  },
  {
    fixture: "portrait-strip-500x4000.jpg",
    pans: { key: "ArrowUp", axis: "y" },
    pinned: { key: "ArrowLeft", axis: "x" },
  },
] as const;

/**
 * `keyboardStep={8}` is what `image-crop-dialog.tsx` passes, so a full arrow press moves 8 container
 * pixels on an axis with headroom.
 */
const KEYBOARD_STEP_PX = 8;

/**
 * The pinned axis has SUB-PIXEL slack, and this is the band that separates a clamp from a pan.
 *
 * MEASURED on `panorama-4000x500.jpg` at a 320px stage (2026-08-25): the media renders 288 x 36 and
 * the crop square is 34.1875, so `restrictPosition`'s vertical bound is (36 − 34.1875) / 2 ≈ 0.91px
 * per side — and the observed displacement after `ArrowUp` was **exactly 0px**. Either reading is a
 * clamp; neither is a pan. What is asserted is that an 8px REQUEST produced at most 1px of movement,
 * while the same press on the same image's free axis produced the full 8 — so the comparison is
 * between two live keys rather than between a key and silence.
 */
const PINNED_TOLERANCE_PX = 1;

test.describe("CROP-01 / D-178 — the stage pans by keyboard, with the library's clamp intact", () => {
  for (const row of AXIS_FIXTURES) {
    test(`${row.fixture}: ${row.pans.key} pans ${row.pans.axis}, ${row.pinned.key} is clamped on ${row.pinned.axis}`, async ({
      page,
    }) => {
      await signUpAndReachProfile(page);
      await pick(page, row.fixture);
      await expect(stageOf(page)).toBeVisible();
      await settleAnimations(page);

      // (a) THE STAGE IS FOCUSABLE WITHOUT A POINTER.
      await tabToStage(page);
      const focusedLabel = await page.evaluate(() =>
        document.activeElement?.getAttribute("aria-label"),
      );
      expect(
        focusedLabel,
        "the crop stage is not `document.activeElement` after the tab walk reported reaching it.",
      ).toBe(AVATAR_POSITION_LABEL);

      const start = await readCropOffset(page);

      // (a, continued) THE CROP MOVES. A CHANGE is asserted, not a pixel count — the count is the
      // library's business and is measured separately below.
      await page.keyboard.press(row.pans.key);
      const panned = await readCropOffset(page);
      const panDelta = Math.abs(panned[row.pans.axis] - start[row.pans.axis]);
      expect(
        panDelta,
        `${row.fixture}: ${row.pans.key} moved the crop by ${panDelta}px on the free ${row.pans.axis} ` +
          "axis. The stage is pannable without a pointer or it is not accessible — 999.2 § 2g's " +
          "requirement survives D-178 unchanged; only the modifier's direction moved.",
      ).toBeGreaterThan(0);

      // (b) THE PINNED AXIS STAYS PINNED. `restrictPosition` clamping is exactly the behaviour a
      // hand-rolled `onKeyDown` would have silently discarded, and D-178 forbids authoring one
      // precisely to keep it.
      const beforePin = await readCropOffset(page);
      await page.keyboard.press(row.pinned.key);
      await page.keyboard.press(row.pinned.key);
      const afterPin = await readCropOffset(page);
      const pinDelta = Math.abs(afterPin[row.pinned.axis] - beforePin[row.pinned.axis]);
      expect(
        pinDelta,
        `${row.fixture}: two ${row.pinned.key} presses moved the crop ${pinDelta}px on the PINNED ` +
          `${row.pinned.axis} axis, where the source has no room. That is ${KEYBOARD_STEP_PX * 2}px ` +
          "of request arriving as movement — `restrictPosition` is not clamping, and IC-04's " +
          "guarantee that the framing cannot leave the image goes with it.",
      ).toBeLessThanOrEqual(PINNED_TOLERANCE_PX);
    });
  }

  // (c) SHIFT IS A FINE ADJUST, NOT A COARSE ONE — the assertion that makes D-178 verifiable.
  test("Shift makes the step FINER, which is the shipped contract D-178 accepted", async ({
    page,
  }) => {
    await signUpAndReachProfile(page);
    await pick(page, "panorama-4000x500.jpg");
    await expect(stageOf(page)).toBeVisible();
    await settleAnimations(page);
    await tabToStage(page);

    const origin = await readCropOffset(page);
    await page.keyboard.press("ArrowLeft");
    const afterPlain = await readCropOffset(page);
    const plainStep = Math.abs(afterPlain.x - origin.x);

    await page.keyboard.press("Shift+ArrowLeft");
    const afterShift = await readCropOffset(page);
    const shiftStep = Math.abs(afterShift.x - afterPlain.x);

    // Non-vacuity first: if Shift moved nothing at all, "smaller" would be trivially true and the
    // modifier would be broken rather than fine.
    expect(
      shiftStep,
      `Shift+ArrowLeft moved the crop 0px. A modifier that disables the key is not a fine adjust, ` +
        "and D-178 accepted a FINER step, not an inert one.",
    ).toBeGreaterThan(0);

    // ⚠ THE CONTRACT CHANGE, STATED PLAINLY. `react-easy-crop@6.2.3` does `step *= 0.2` on Shift.
    // With `keyboardStep={8}` that is 8px plain and 1.6px with Shift — MEASURED 2026-08-25, both
    // values exactly. 999.2 § 2g asked for the opposite (8px arrow, 24px COARSE Shift), and D-178
    // amended § 2g to match what ships: Shift-as-fine-adjust is the platform convention in every
    // design tool, the accessibility requirement is met either way, and matching § 2g's letter would
    // cost a hand-rolled handler that discards the clamp asserted above. THIS ASSERTION IS WHAT
    // MAKES THAT ACCEPTANCE VERIFIABLE rather than merely written down.
    expect(
      shiftStep,
      `Shift+ArrowLeft moved ${shiftStep}px against a plain ArrowLeft's ${plainStep}px. D-178 ` +
        "accepted the library's Shift-as-FINE-adjust (`step *= 0.2`) over 999.2 § 2g's coarse one. " +
        "A Shift step that is not smaller means either a custom handler was layered on (which " +
        "D-178 forbids) or `keyboardStep` moved.",
    ).toBeLessThan(plainStep);

    expect(
      plainStep,
      `a plain ArrowLeft moved ${plainStep}px; \`keyboardStep={8}\` is what the dialog passes.`,
    ).toBeCloseTo(KEYBOARD_STEP_PX, 3);
    expect(
      shiftStep,
      `Shift+ArrowLeft moved ${shiftStep}px; the library's 0.2x multiplier on an 8px step is 1.6px.`,
    ).toBeCloseTo(KEYBOARD_STEP_PX * 0.2, 3);
  });
});

// ═════════════════════════════════════════════════════════════════════════════════════════════════
// (d) NO CUSTOM HANDLER EXISTS — A SOURCE ASSERTION, AND THE RIGHT INSTRUMENT FOR IT
// ═════════════════════════════════════════════════════════════════════════════════════════════════
//
// The failure D-178 guards against is the PRESENCE OF CODE, not a behaviour a browser can show. A
// hand-rolled handler that happened to reproduce today's steps would pass every assertion above and
// would still have thrown away `restrictPosition` and the `emitCropData` re-pairing on some path
// nobody tested. A browser cannot see the difference; the file can.

test("D-178: the crop dialog layers NO key handling over the library's", () => {
  const source = readFileSync(
    path.join(__dirname, "..", "src", "components", "profile", "image-crop-dialog.tsx"),
    "utf8",
  );

  // A SANITY FLOOR BEFORE THE NEGATIVES. Three "this string is absent" assertions are all vacuously
  // true against an empty read, a moved file or a typo'd path — this is the line that makes the
  // three below statements about the shipped component.
  expect(
    source,
    "`image-crop-dialog.tsx` was read but does not contain the cropper. Every assertion below is " +
      "about the ABSENCE of a string, and absence is free in a file that is not the right one.",
  ).toContain("react-easy-crop");

  for (const forbidden of ["onKeyDown", "onKeyUp", 'addEventListener("keydown")']) {
    expect(
      source.includes(forbidden),
      `\`image-crop-dialog.tsx\` contains \`${forbidden}\`. D-178: the keyboard pan is the ` +
        "library's own, unlayered and unsuppressed. A handler in `cropperProps` OVERRIDES the " +
        "library's (that object is spread after the built-in props), which loses `restrictPosition` " +
        "clamping and the `onInteractionStart`/`emitCropData` pairing that makes `onCropComplete` " +
        "fire after a keyboard nudge — so the crop rectangle the encoder reads would go stale.",
    ).toBe(false);
  }
});

// ═════════════════════════════════════════════════════════════════════════════════════════════════
// (e) THE FOCUS INDICATOR ON THE STAGE — VISIBLE, AND ITS COLOUR CARRIES NO ALPHA
// ═════════════════════════════════════════════════════════════════════════════════════════════════
//
// ⚠ A MEASURED FINDING THAT CHANGES WHICH MECHANISM IS DOING THE WORK, RECORDED RATHER THAN ABSORBED.
//
// `image-crop-dialog.tsx` passes DS-05's recipe to the crop area through
// `classes.cropAreaClassName`, and 16-RESEARCH § A5 flagged that route as the right INTENT with no
// guarantee of winning: the library injects its stylesheet UNLAYERED into the document head while
// Tailwind v4 utilities live in a cascade layer, and unlayered beats layered.
//
// MEASURED HERE, 2026-08-25, on the focused stage. § A5's risk is REAL:
//
//   box-shadow : rgba(0, 0, 0, 0.5) 0px 0px 0px 139986px      ← the LIBRARY's scrim, not a ring
//   outline    : auto 1px lab(36.2 0 0.00000596046)           ← a real, opaque indicator
//   class      : reactEasyCrop_CropArea reactEasyCrop_CropAreaRound focus-visible:ring-2 …
//
// Tailwind's `ring-*` compiles to `box-shadow`, and `.reactEasyCrop_CropArea`'s own unlayered
// `box-shadow: 0 0 0 9999em` (IC-04's scrim) occupies that property and wins. **The ring half of
// DS-05 does not paint on this element.** What paints is the STYLESHEET half — `globals.css`'s
// base-layer `* { @apply border-border outline-ring }` colouring the UA's own focus outline in
// `--ring` at FULL alpha (`oklch(0.556 0 0)` → `lab(36.2 …)`, no alpha component). DS-05 is
// satisfied through its other half, which is why this reads as a correct surface rather than a
// ringless one.
//
// WHAT THIS FILE THEREFORE ASSERTS, AND WHAT IT DELIBERATELY DOES NOT. It asserts the two things
// that must be true however the cascade lands: an indicator IS painted, and its colour carries no
// alpha. It does NOT assert "the box-shadow is the scrim" — that would encode today's cascade as a
// requirement and go red the day somebody lands the winning route, which is the opposite of what is
// wanted. Filed as D5 in `deferred-items.md` for plan 16-14, which owns the route decision and its
// inventory row; `image-crop-dialog.tsx`'s own header already names 16-13 as where it would be
// measured, and this is that measurement.

/**
 * A `ring-*` compiles to a FIVE-layer box-shadow of which three layers are fully transparent
 * placeholders, so "the shadow string is not `none`" is not the same claim as "something is drawn".
 * Strip every fully-transparent layer and something with a colour must remain.
 *
 * ⚠ RE-DECLARED, NOT IMPORTED, and that is forced rather than chosen: these two live at
 * `e2e/auth-keyboard.spec.ts:491-492`, and importing from a spec file would register that file's
 * whole suite as a side effect of this one. `helpers/focus.ts` is where they would belong if a third
 * consumer appeared; two is not yet the threshold that file was extracted at.
 */
const FULLY_TRANSPARENT = /rgba\(\s*\d+\s*,\s*\d+\s*,\s*\d+\s*,\s*0\s*\)/g;
const A_COLOUR = /(rgb|rgba|hsl|hsla|lab|lch|oklab|oklch|color)\(|#[0-9a-f]{3}/i;

/** Any colour function carrying an explicit alpha — the dilution `focus-recipe.test.ts:115` deletes. */
const ALPHA_BEARING =
  /(rgba?\([^)]*[,/]\s*(0?\.\d+|0)\s*\)|hsla?\([^)]*[,/]\s*(0?\.\d+|0)\s*\)|(oklch|oklab|lab|lch|color)\([^)]*\/\s*(0?\.\d+|0)[^)]*\))/i;

test.describe("CROP-01 / DS-05 — the focused stage draws a visible, undiluted indicator", () => {
  test("the stage draws an indicator on keyboard focus, and its colour carries no alpha", async ({
    page,
  }) => {
    await signUpAndReachProfile(page);
    await pick(page, "square-400.png");
    await expect(stageOf(page)).toBeVisible();
    await settleAnimations(page);

    await tabToStage(page);

    const reading = await readFocus(page);
    expect(reading, "nothing holds focus after the tab walk reached the stage").not.toBeNull();
    if (reading === null) return;
    expect(
      reading.label,
      "the focused element is not the crop stage, so the indicator below belongs to something else.",
    ).toContain(AVATAR_POSITION_LABEL.slice(0, 14));

    // GATE-A11Y's focus half, through the SAME instrument `e2e/auth-keyboard.spec.ts` applies to its
    // 59 stops — one criterion for the whole suite, never a second one that happens to agree today.
    expectRing(reading, "the crop stage");

    const focused = await computed(stageOf(page), ["outline-style", "outline-width", "outline-color"]);

    // THE UNFOCUSED BASELINE IS TAKEN AFTERWARDS, BY TABBING OFF THE STAGE, AND THE ORDER IS A
    // CORRECTION RATHER THAN A PREFERENCE. The first draft read the baseline BEFORE the tab walk and
    // failed on a correct tree: `ResponsiveDialog` opens with the crop area already holding focus —
    // it is the first tabbable element in `DialogContent` — so the "unfocused" reading was the
    // focused one and the difference check compared a state against itself (`auto 1px` both sides).
    //
    // The comparison is load-bearing and not ceremony. `expectRing` accepts any non-`none`
    // box-shadow, and THIS ELEMENT DRAWS A PERMANENT ONE: `.reactEasyCrop_CropArea`'s
    // `box-shadow: 0 0 0 9999em` is IC-04's scrim and is painted whether the stage has focus or not.
    // An indicator check that did not compare states would be satisfied by the scrim alone, on a
    // stage that drew nothing at all on focus.
    await page.keyboard.press("Tab");
    const unfocused = await computed(stageOf(page), ["outline-style", "outline-width"]);

    expect(
      `${focused["outline-style"]} ${focused["outline-width"]}`,
      "the crop stage draws the same outline focused and unfocused, so what it draws is decoration " +
        `rather than an indicator (unfocused: ${unfocused["outline-style"]} ` +
        `${unfocused["outline-width"]}).`,
    ).not.toBe(`${unfocused["outline-style"]} ${unfocused["outline-width"]}`);

    // THE COLOUR IS REALLY PAINTED — not a transparent placeholder layer.
    const drawnShadow = reading.boxShadow.replace(FULLY_TRANSPARENT, "").trim();
    const outlineIsDrawn =
      focused["outline-style"] !== "none" && parseFloat(focused["outline-width"]) > 0;
    expect(
      outlineIsDrawn || A_COLOUR.test(drawnShadow),
      "the crop stage's focus indicator has no colour left once fully-transparent layers are " +
        `stripped. outline: ${focused["outline-style"]} ${focused["outline-width"]}; ` +
        `box-shadow: ${reading.boxShadow}. A ring whose colour went transparent still hands a long ` +
        "non-`none` string to a naive check and passes — this is the assertion that does not.",
    ).toBe(true);

    // NO ALPHA. `ring-ring/50` (and its stylesheet twin `outline-ring/50`) is the shadcn default
    // this repo exists to delete: the half-alpha form compiles to
    // `color-mix(in oklab, var(--ring) 50%, transparent)` and composites to 1.54:1 against white —
    // arithmetic no value of `--ring` can rescue (`globals.css:499-513`, `focus-recipe.test.ts:115`).
    expect(
      ALPHA_BEARING.test(focused["outline-color"]),
      `the crop stage's focus outline is \`${focused["outline-color"]}\`, which carries an alpha ` +
        "channel. DS-05 removed the 50% modifier from the outline colour for an arithmetic reason " +
        "rather than an aesthetic one, and a diluted indicator on the ONE control a keyboard user " +
        "pans the photo with is the worst place to reinstate it.",
    ).toBe(false);
  });
});

// A GUARD ON THE HARNESS ITSELF, not on the product: every case above navigates to the dev server,
// and a suite that silently ran against nothing would report the same green as a suite that ran.
test("harness: the dev server this file measures is the one the helpers name", async ({ page }) => {
  const response = await page.goto(`${BASE}/`);
  expect(response?.status(), `${BASE} did not answer 200`).toBe(200);
});
