const assert = require("node:assert/strict");
const m = require("./journey-model");
let state = m.start();
state = m.choose(state, "Pickleball");
state = m.choose(state, "Makati");
assert.equal(state.step, 2);
state = m.back(state);
assert.equal(state.answers.activity, "Pickleball");
assert.equal(state.step, 1);
state = m.choose(state, "Ortigas");
state = m.choose(state, "6 people");
assert.equal(state.screen, "ready");
state = m.edit(state, "party");
assert.equal(state.step, 2);
assert.equal(state.answers.location, "Ortigas");
state = m.choose(state, "4 people");
state = m.submit(state);
assert.equal(state.screen, "results");
assert.deepEqual(m.cancel(state), m.empty());
console.log("journey-model: 8 state transitions passed");
