import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "@/components/theme/theme-provider";
import { ThemeQueryParam } from "@/components/theme/theme-query-param";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/**
 * DS-14 — the app's own identity. Until this edit, every screen of a money-handling marketplace
 * opened in a browser tab carrying the scaffold's name and a "generated by" description: the app's
 * name in a user's window switcher, their bookmarks and their history was the name of the tool that
 * created the repo. The scaffold strings themselves are deliberately not repeated in this file, and
 * tests/design/scaffold-residue.test.ts asserts none of them survives anywhere in this export.
 *
 * The base-URL entry below is the one line here that is not cosmetic: it is what makes every LATER
 * relative Open Graph / Twitter image URL resolve to an absolute one. Without it Next warns and a
 * relative `openGraph.images` entry silently produces a broken share card — a failure only ever
 * discovered by someone pasting a listing link into a chat. It reads `NEXT_PUBLIC_APP_URL` so a
 * deploy gets its real origin, and falls back to the dev origin so a fresh clone needs no env var.
 *
 * `title` is an object rather than a bare string so child routes get the "%s · FitOut" suffix for
 * free — the invite page (src/app/invite/[token]/page.tsx:60) already hand-wrote that suffix, and
 * the template is what stops the next twenty routes each hand-writing it slightly differently.
 */
export const metadata: Metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000"),
  title: { default: "FitOut", template: "%s · FitOut" },
  description: "Book gyms, courts and studios by the hour.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // THE BARE ATTRIBUTE ON <html> BELOW IS LOAD-BEARING (D-07), not belt-and-braces. next-themes
    // injects an inline pre-paint script that mutates `document.documentElement`'s `data-theme`
    // BEFORE React hydrates, so the server-rendered <html> and the client's differ by construction
    // on EVERY load. Without it React logs a hydration warning every single time the app opens — and
    // a console that always has a warning in it is a console nobody reads, which is how the next
    // real warning gets missed. Removing it does not fix a mismatch; it just makes a deliberate and
    // unavoidable one noisy.
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* THEME-01 — the single mount point for the whole app. Every route, every layout and all
            FOUR <Toaster /> mounts ((app)/layout.tsx:103, (host)/host/listings/page.tsx:77,
            .../[id]/availability/page.tsx:140 and .../[id]/edit/wizard.tsx:586) already sit under
            this root layout, so one provider here covers all of them and no Toaster mount moves. */}
        <ThemeProvider>
          <ThemeQueryParam />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
