import "server-only";

// "Is this caller staff?" — as ONE expression, plus the two callers that do different jobs with the
// answer (OPS-01, OPS-02, D-214/D-216/D-219).
//
// ── WHAT THIS MODULE IS, AND WHAT IT DELIBERATELY IS NOT ──────────────────────────────────────────
//
// FitOut has had a `role` column on `user` since Phase 1 and has never read it. `src/lib/auth.ts:112`
// declares it as an additionalField — `{ type: "string", required: false, defaultValue: "user",
// input: false }` — with the comment "admin slot for later". This is later. Nothing is added to the
// auth config to make staff standing real: the field already rides `session.user` (additionalFields
// are returned by default), and `input: false` already makes it unwritable from any client body.
//
// THE BETTER AUTH ADMIN PLUGIN WAS CONSIDERED AND REJECTED, and the reason is a measurement rather
// than a preference (18-RESEARCH § F1b, read out of the installed package at
// `node_modules/better-auth/dist/plugins/admin/`):
//
//   - Its own `role` declaration is attribute-identical to the one already in `src/lib/auth.ts:112`
//     (`type:"string"`, `required:false`, `input:false`). For the field this module actually reads,
//     the plugin adds nothing at all.
//   - `routes.mjs` mounts FIFTEEN privileged endpoints, and `src/app/api/auth/[...all]/route.ts` is
//     `toNextJsHandler(auth)` — a catch-all. Adding the plugin PUBLISHES ALL FIFTEEN INSTANTLY,
//     among them `set-role` (a role-grant HTTP endpoint, when D-217 says grants are CLI-only),
//     `impersonate-user` (session impersonation on a marketplace that moves real money),
//     `set-user-password` and `remove-user`. Each would then need its own rate-limit rule in
//     `auth.ts`'s customRules and its own test, to buy back the security it just spent.
//   - It also adds three columns to `user` and one to `session` — both Better-Auth-owned tables that
//     `src/lib/db/schema.ts:1-4` says are regenerated by the CLI and must not be hand-edited.
//
// So the plugin is a net loss and its absence is a DECISION recorded here, not an oversight a future
// reader should "fix".
//
// ── THE INVARIANT THIS MODULE'S CORRECTNESS HANGS ON: NO COOKIE CACHE ──────────────────────────────
//
// `auth.api.getSession()` reads the DATABASE on every call, because `session.cookieCache` is not
// configured in `src/lib/auth.ts` (a repo-wide grep for `cookieCache` returns exactly one hit, in a
// comment at `src/lib/session-check.ts:20`). That is what makes a staff grant — and, far more
// importantly, a staff REVOCATION — take effect on the very next request with no session-invalidation
// step to remember.
//
// STATED THE WAY `src/lib/auth.ts:73` STATES `revokeSessionsOnPasswordReset`: the DEFAULT is what we
// depend on, so the dependency has to be written down where the dependant lives. Turning cookie
// caching on — an ordinary-looking performance change, one line in the auth config — would let a
// REVOKED staff grant keep opening every ops surface for the cache TTL, and nothing in this file
// would go red. If you are here to enable it, this module is what you have to fix first.
//
// ── THE PREDICATE IS POSITIVE EQUALITY, BECAUSE THE COLUMN IS NULLABLE ────────────────────────────
//
// `src/lib/db/schema.ts:45` is `role: text("role").default("user")` — no `.notNull()`. A DEFAULT is
// not a constraint: every row inserted by a path that names the column explicitly (a migration, a
// seed, a hand-run UPDATE, a future Better Auth adapter change) may carry NULL. The predicate is
// therefore `role === "staff"` and never the inverted form against "user", which would read a NULL
// as staff and hand the ops console to every row the default did not reach. Fail closed, positively.

import { cache } from "react";
import { notFound } from "next/navigation";
import { headers } from "next/headers";

import { auth } from "@/lib/auth";

/** The authenticated staff actor — the `actorId` every ops audit row is written with (OPS-03). */
export type StaffActor = { id: string };

/**
 * THE ONE EXPRESSION. Resolve the caller's staff standing, or `null`.
 *
 * Both the layout that sets the STATUS LINE and every page/action that makes the DECISION go through
 * here, so the rule cannot drift between them — the same reason `isPubliclyViewable` has exactly one
 * definition shared by `src/app/listings/[id]/(detail)/layout.tsx` and the page beneath it
 * (`src/lib/listing/public-listing.ts:70-76`).
 *
 * `cache()` is not an optimisation so much as the thing that makes D-216's belt-and-braces free: it
 * is request-scoped, so the layout's assert and the page's own guard and the action's guard are ONE
 * session read per request, however many callers ask.
 *
 * The local widening of `session.user` is the cast every `additionalFields` reader in this repo
 * already writes (`src/app/(host)/host/layout.tsx:47-50` for canBook/canHost) — the fields are on the
 * row and on the response, but not on Better Auth's base session-user type.
 */
export const readStaff = cache(async (): Promise<StaffActor | null> => {
  const session = await auth.api.getSession({ headers: await headers() });
  if (!session?.user) return null;

  const u = session.user as typeof session.user & { role?: string | null };

  // POSITIVE STRING EQUALITY, and see the header: `role` is NULLABLE, so the inverted test against
  // the default value would promote every NULL-role account to staff.
  return u.role === "staff" ? { id: u.id } : null;
});

/**
 * LAYER 2 AND LAYER 3 — **THE SECURITY BOUNDARY** (D-216, OPS-02).
 *
 * Called by EVERY `(ops)` page and EVERY ops server action, independently, every time. Not by the
 * layout instead of them: Next's own authentication guide says a layout "does not control whether
 * the rest of the route renders … a layout that hides or swaps them does not stop them from running
 * or from appearing in the RSC Payload", and separately that Server Actions must be treated "with
 * the same security considerations as public-facing API endpoints". `src/proxy.ts:1-7` says the
 * same thing about itself from the other end. There is no third place this decision can live.
 *
 * A refused caller gets `notFound()` — byte-identical to what a URL nobody ever routed produces —
 * never a 403 and never a bounce to /login (D-219). A distinguishable refusal is an EXISTENCE
 * ORACLE: it tells a prober that `/ops/...` is a real surface worth attacking, which is exactly the
 * information the guard exists to withhold. For the same reason there must be no `(ops)`-scoped
 * `not-found.tsx` — a distinct 404 body under `/ops` is the same oracle wearing a different hat.
 *
 * Returns the staff id so every caller already holds the AUTHENTICATED `actorId` that OPS-03's audit
 * row needs — the phase's answer to `audit.resolved_by` being "asserted, not authenticated".
 */
export async function requireStaff(): Promise<StaffActor> {
  const staff = await readStaff();
  if (!staff) notFound();
  return staff;
}

/**
 * LAYER 1 — **NOT THE SECURITY BOUNDARY.** Said in `src/proxy.ts:1`'s own words: this is
 * OPTIMISTIC ONLY, it makes no authoritative decision anything may rely on, and nothing sensitive
 * may be gated on it alone. `requireStaff()` above is the gate; this is a status line.
 *
 * WHAT IT IS FOR, precisely. Every `(ops)` page reads the database, so it is an async page, so
 * `tests/design/loading-coverage.test.ts` — which is build-blocking (`npm run build` = `lint &&
 * test:design && next build`) — REQUIRES it to have a `loading.tsx` beside it. `loading.tsx` is a
 * `<Suspense>` boundary, and Next states the consequence plainly: "Because the check runs inside the
 * `<Suspense>` boundary, the response has already begun streaming as a `200`, and the status can't
 * change once streaming has started." A truly nonexistent route answers a hard 404. So a page-level
 * guard alone leaves the two telling each other apart by one number — `curl -o /dev/null -w
 * '%{http_code}'` is the whole attack — and D-219 is violated without a single byte of ops data
 * leaking. Worse, per Next, the not-found body "renders in place of the streamed-in content, even
 * though the page shell has already been sent": any chrome the ops layout renders would frame the
 * 404 with a visible "Ops" header.
 *
 * A LAYOUT is above that boundary, so awaiting here blocks the flush and the status line is still
 * open when the refusal runs. This is the identical mechanism, and the identical fix, that
 * `src/lib/listing/public-listing.ts` documents for `/listings/[id]` — including the two plausible
 * repairs that were MEASURED not to work (asserting in `generateMetadata` is still too late; deleting
 * `loading.tsx` works and trips the build-blocking gate). Do not rediscover that the hard way.
 *
 * ⚠ CALL THIS FROM THE `(ops)` LAYOUT, IN ADDITION TO — never instead of — the per-page and
 * per-action `requireStaff()`.
 */
export const assertStaff = cache(async (): Promise<void> => {
  if (!(await readStaff())) notFound();
});
