// DS-14 (part 1 of 2) — the app identifies itself as FitOut.
//
// Until this plan, every screen in a money-handling marketplace opened in a browser tab reading
// **"Create Next App"** with the meta description **"Generated by create next app"**. That is not a
// cosmetic nit: the tab title is the app's name in a user's window switcher, in their bookmarks, and
// in their browser history, and the description is what a search engine or a link preview quotes.
// Scaffold residue is the kind of defect that survives an entire milestone precisely because nobody
// owns it — so it gets a permanent test rather than a one-off edit.
//
// PART 2 IS PLAN 10-15 and will EXTEND THIS SAME FILE: the five unreferenced `public/*.svg` starter
// assets and `src/app/favicon.ico`. Those deletions are deliberately NOT asserted here — this file
// currently covers the metadata half only, and a reader must not mistake a green run for "all
// scaffold residue is gone".
//
// THE SECOND DESCRIBE covers D-07's half of the same edit, because the metadata and the provider
// mount landed in the same file in the same task and a revert of that file would silently take the
// theme runtime with it. Those two assertions read the RAW SOURCE TEXT rather than the module,
// because what is being asserted is a structural property of the file (an attribute on <html>, a
// component wrapping children) that no runtime value exposes.
//
// NOT COVERED — real blind spots, listed so the next reader under-trusts this file:
//   • That the title actually PAINTS in a browser tab. Next composes metadata at render time; this
//     asserts the export it composes from. Phase 11's GATE-01 pass sees the real tab.
//   • That `NEXT_PUBLIC_APP_URL` is set correctly in any deployed environment. Only the fallback is
//     exercised here.
//   • That `suppressHydrationWarning` actually suppresses anything — that needs a real React
//     hydration pass against a mutated <html>, which jsdom cannot stage faithfully.

import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, it, expect, vi } from "vitest";

// `next/font/google` is a compile-time construct: outside the Next compiler `Geist(...)` is not a
// function at all, so importing the layout module throws before `metadata` is reachable. The mock
// returns the same shape the real loader does (`{ variable, className }`), which is all layout.tsx
// reads. Nothing about DS-14 depends on the font, and DS-01 (which does) is asserted against the
// compiled stylesheet in font-cycle.test.ts, not through this import.
vi.mock("next/font/google", () => ({
  Geist: (opts: { variable: string }) => ({
    variable: opts.variable,
    className: "mock-geist-sans",
  }),
  Geist_Mono: (opts: { variable: string }) => ({
    variable: opts.variable,
    className: "mock-geist-mono",
  }),
}));

const LAYOUT_PATH = resolve(__dirname, "../../src/app/layout.tsx");

/** The exact strings the create-next-app scaffold ships. Neither may survive anywhere in the export. */
const SCAFFOLD_STRINGS = ["Create Next App", "Generated by create next app"] as const;

/**
 * The title template's separator is U+00B7 MIDDLE DOT, written here as an escape ON PURPOSE. If it
 * were pasted literally, a file re-saved in the wrong encoding would corrupt the expectation and the
 * assertion in the same stroke, and the test would keep passing against a mojibake tab title.
 */
const TITLE_TEMPLATE = "%s · FitOut";
const DESCRIPTION = "Book gyms, courts and studios by the hour.";

async function loadMetadata() {
  const mod = await import("@/app/layout");
  return mod.metadata;
}

/** Every string reachable in the metadata export, however deeply nested. */
function allStrings(value: unknown, out: string[] = []): string[] {
  if (typeof value === "string") out.push(value);
  else if (value instanceof URL) out.push(value.href);
  else if (Array.isArray(value)) for (const v of value) allStrings(v, out);
  else if (value && typeof value === "object")
    for (const v of Object.values(value)) allStrings(v, out);
  return out;
}

describe("DS-14 — the identity metadata is FitOut's, not create-next-app's", () => {
  it("sets title.default to FitOut", async () => {
    const metadata = await loadMetadata();
    // An object title (not a bare string) is what gives child routes the template for free.
    expect(metadata.title).toBeTypeOf("object");
    expect((metadata.title as { default: string }).default).toBe("FitOut");
  });

  it("sets title.template so every child route gets the suffix without hand-writing it", async () => {
    const metadata = await loadMetadata();
    expect((metadata.title as { template: string }).template).toBe(TITLE_TEMPLATE);
  });

  it("sets the real meta description", async () => {
    const metadata = await loadMetadata();
    expect(metadata.description).toBe(DESCRIPTION);
  });

  it("sets metadataBase to an absolute URL, so relative OG images resolve", async () => {
    // The failure this prevents is invisible locally and only shows up when someone pastes a
    // listing link into a chat and gets a broken share card.
    const metadata = await loadMetadata();
    const base = metadata.metadataBase;
    // Narrowed rather than optional-chained: Next types this `string | URL | null`, and a plain
    // string would type-check at the call site while defeating the whole point of the field.
    expect(base).toBeInstanceOf(URL);
    if (!(base instanceof URL)) throw new Error("metadataBase is not a URL");
    expect(base.protocol).toMatch(/^https?:$/);
    expect(base.href).not.toBe("");
  });

  it("carries no create-next-app scaffold string anywhere in the export", async () => {
    // Asserted over EVERY nested string rather than over `title` and `description` specifically,
    // so residue reappearing in openGraph, twitter or appleWebApp later is caught by this same test.
    const metadata = await loadMetadata();
    const strings = allStrings(metadata);
    for (const scaffold of SCAFFOLD_STRINGS) {
      const offenders = strings.filter((s) => s.includes(scaffold));
      expect(offenders, `scaffold string "${scaffold}" survives in: ${offenders.join(" | ")}`).toEqual([]);
    }
  });
});

describe("D-07 — the theme runtime is mounted in the same root layout", () => {
  it("puts suppressHydrationWarning on the root element", async () => {
    // Load-bearing, not belt-and-braces: next-themes' pre-paint script mutates documentElement
    // before React hydrates, so the mismatch is deliberate and permanent.
    const source = readFileSync(LAYOUT_PATH, "utf8");
    expect(source).toContain("suppressHydrationWarning");
  });

  it("mounts the ThemeProvider around the tree", async () => {
    const source = readFileSync(LAYOUT_PATH, "utf8");
    // Import plus JSX — a bare import with no mount would satisfy a single occurrence.
    expect(source.split("ThemeProvider").length - 1).toBeGreaterThanOrEqual(2);
    expect(source).toMatch(/<ThemeProvider>/);
  });

  // -------------------------------------------------------------------------
  // Guard the guard (T-10-06): the two assertions above are `toContain` over a
  // file read. A path typo returning "" would throw, but a truncated or
  // half-written file would not — and several assertions in this file are
  // negatives, which an empty read passes trivially.
  // -------------------------------------------------------------------------
  it("guard-the-guard: the layout source really was read", () => {
    const source = readFileSync(LAYOUT_PATH, "utf8");
    expect(source.length).toBeGreaterThan(500);
    expect(source).toContain("<html");
  });
});
