// DS-14 — the app identifies itself as FitOut, and NO create-next-app residue survives. BOTH HALVES.
//
// Until plan 10-05, every screen in a money-handling marketplace opened in a browser tab reading
// **"Create Next App"** with the meta description **"Generated by create next app"**. That is not a
// cosmetic nit: the tab title is the app's name in a user's window switcher, in their bookmarks, and
// in their browser history, and the description is what a search engine or a link preview quotes.
// Scaffold residue is the kind of defect that survives an entire milestone precisely because nobody
// owns it — so it gets a permanent test rather than a one-off edit.
//
// PART 2 LANDED IN PLAN 10-15 AND EXTENDS THIS SAME FILE (the third describe below), which is what
// 10-05's header promised: the five unreferenced `public/*.svg` starter assets and
// `src/app/favicon.ico` are DELETED, and the two generated themed icons stand in their place. This
// file now covers the whole requirement, so a green run may finally be read as "no scaffold residue
// survives" rather than "the metadata half is clean".
//
// WHY THE DELETIONS ARE ASSERTED AT ALL, given they already happened. A deletion has no symptom. The
// realistic way `favicon.ico` comes back is not a revert — it is `npx create-next-app` output being
// copied in, or a merge resurrecting a file nobody is looking for. And leaving it alongside an SVG
// icon is worse than either alone: with both present a browser picks whichever it likes, so the tab
// would show the scaffold's mark on some machines and FitOut's on others, non-reproducibly.
//
// THE SECOND DESCRIBE covers D-07's half of the same edit, because the metadata and the provider
// mount landed in the same file in the same task and a revert of that file would silently take the
// theme runtime with it. Those assertions read the RAW SOURCE TEXT rather than the module,
// because what is being asserted is a structural property of the file (an attribute on <html>, a
// component wrapping children) that no runtime value exposes.
//
// NOT COVERED — real blind spots, listed so the next reader under-trusts this file:
//   • That the title actually PAINTS in a browser tab. Next composes metadata at render time; this
//     asserts the export it composes from. Phase 11's GATE-01 pass sees the real tab.
//   • That `NEXT_PUBLIC_APP_URL` is set correctly in any deployed environment. Only the fallback is
//     exercised here.
//   • That `suppressHydrationWarning` actually suppresses anything — that needs a real React
//     hydration pass against a mutated <html>, which jsdom cannot stage faithfully.
//   • That the icon link actually SWAPS when the theme changes. That needs a real browser with a
//     real next-themes pre-paint script; the assertion here is that the component is mounted and is
//     the only declared owner, which is the part a file revert would silently undo. It WAS verified
//     against a production build during 10-15 — one link, court by default, grove when themed, still
//     one after two navigations and a reload — but that probe is not committed, and Phase 11's
//     GATE-01 pass is where a real tab enters the permanent suite.
//   • That the icons are the generator's output BYTE FOR BYTE — that is
//     tests/design/token-drift.test.ts. What is asserted below is the weaker, independent claim that
//     each icon still carries its own theme's brand colour, which is what catches an icon that
//     stopped tracking the token contract without the generator being re-run.

import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, it, expect, vi } from "vitest";

import { THEME_TOKENS } from "../../src/lib/design/tokens.generated";

// `next/font/google` is a compile-time construct: outside the Next compiler `Geist(...)` is not a
// function at all, so importing the layout module throws before `metadata` is reachable. The mock
// returns the same shape the real loader does (`{ variable, className }`), which is all layout.tsx
// reads. Nothing about DS-14 depends on the font, and DS-01 (which does) is asserted against the
// compiled stylesheet in font-cycle.test.ts, not through this import.
vi.mock("next/font/google", () => ({
  Geist: (opts: { variable: string }) => ({
    variable: opts.variable,
    className: "mock-geist-sans",
  }),
  Geist_Mono: (opts: { variable: string }) => ({
    variable: opts.variable,
    className: "mock-geist-mono",
  }),
}));

const LAYOUT_PATH = resolve(__dirname, "../../src/app/layout.tsx");
const FAVICON_SWAP_PATH = resolve(__dirname, "../../src/components/theme/favicon-swap.tsx");
const REPO_ROOT = resolve(__dirname, "../..");

/**
 * The create-next-app assets, relative to the repository root. All six were grep-verified
 * unreferenced anywhere in `src/` before deletion — the single `next.svg` hit was
 * `ui/calendar.tsx:35`'s `rdp-button_next>svg` selector, a false positive on a substring.
 */
const SCAFFOLD_ASSETS = [
  "src/app/favicon.ico",
  "public/file.svg",
  "public/globe.svg",
  "public/next.svg",
  "public/vercel.svg",
  "public/window.svg",
] as const;

/** What replaced them: one generated, themed mark per theme (D-19). */
const GENERATED_ICONS = {
  court: "public/icon-court.svg",
  grove: "public/icon-grove.svg",
} as const;

/** The exact strings the create-next-app scaffold ships. Neither may survive anywhere in the export. */
const SCAFFOLD_STRINGS = ["Create Next App", "Generated by create next app"] as const;

/**
 * The title template's separator is U+00B7 MIDDLE DOT, written here as an escape ON PURPOSE. If it
 * were pasted literally, a file re-saved in the wrong encoding would corrupt the expectation and the
 * assertion in the same stroke, and the test would keep passing against a mojibake tab title.
 */
const TITLE_TEMPLATE = "%s · FitOut";
const DESCRIPTION = "Book gyms, courts and studios by the hour.";

async function loadMetadata() {
  const mod = await import("@/app/layout");
  return mod.metadata;
}

/** Every string reachable in the metadata export, however deeply nested. */
function allStrings(value: unknown, out: string[] = []): string[] {
  if (typeof value === "string") out.push(value);
  else if (value instanceof URL) out.push(value.href);
  else if (Array.isArray(value)) for (const v of value) allStrings(v, out);
  else if (value && typeof value === "object")
    for (const v of Object.values(value)) allStrings(v, out);
  return out;
}

describe("DS-14 — the identity metadata is FitOut's, not create-next-app's", () => {
  it("sets title.default to FitOut", async () => {
    const metadata = await loadMetadata();
    // An object title (not a bare string) is what gives child routes the template for free.
    expect(metadata.title).toBeTypeOf("object");
    expect((metadata.title as { default: string }).default).toBe("FitOut");
  });

  it("sets title.template so every child route gets the suffix without hand-writing it", async () => {
    const metadata = await loadMetadata();
    expect((metadata.title as { template: string }).template).toBe(TITLE_TEMPLATE);
  });

  it("sets the real meta description", async () => {
    const metadata = await loadMetadata();
    expect(metadata.description).toBe(DESCRIPTION);
  });

  it("sets metadataBase to an absolute URL, so relative OG images resolve", async () => {
    // The failure this prevents is invisible locally and only shows up when someone pastes a
    // listing link into a chat and gets a broken share card.
    const metadata = await loadMetadata();
    const base = metadata.metadataBase;
    // Narrowed rather than optional-chained: Next types this `string | URL | null`, and a plain
    // string would type-check at the call site while defeating the whole point of the field.
    expect(base).toBeInstanceOf(URL);
    if (!(base instanceof URL)) throw new Error("metadataBase is not a URL");
    expect(base.protocol).toMatch(/^https?:$/);
    expect(base.href).not.toBe("");
  });

  it("carries no create-next-app scaffold string anywhere in the export", async () => {
    // Asserted over EVERY nested string rather than over `title` and `description` specifically,
    // so residue reappearing in openGraph, twitter or appleWebApp later is caught by this same test.
    const metadata = await loadMetadata();
    const strings = allStrings(metadata);
    for (const scaffold of SCAFFOLD_STRINGS) {
      const offenders = strings.filter((s) => s.includes(scaffold));
      expect(offenders, `scaffold string "${scaffold}" survives in: ${offenders.join(" | ")}`).toEqual([]);
    }
  });
});

describe("D-07 — the theme runtime is mounted in the same root layout", () => {
  it("puts suppressHydrationWarning on the root element", async () => {
    // Load-bearing, not belt-and-braces: next-themes' pre-paint script mutates documentElement
    // before React hydrates, so the mismatch is deliberate and permanent.
    const source = readFileSync(LAYOUT_PATH, "utf8");
    expect(source).toContain("suppressHydrationWarning");
  });

  it("mounts the ThemeProvider around the tree", async () => {
    const source = readFileSync(LAYOUT_PATH, "utf8");
    // Import plus JSX — a bare import with no mount would satisfy a single occurrence.
    expect(source.split("ThemeProvider").length - 1).toBeGreaterThanOrEqual(2);
    expect(source).toMatch(/<ThemeProvider>/);
  });

  // -------------------------------------------------------------------------
  // Guard the guard (T-10-06): the two assertions above are `toContain` over a
  // file read. A path typo returning "" would throw, but a truncated or
  // half-written file would not — and several assertions in this file are
  // negatives, which an empty read passes trivially.
  // -------------------------------------------------------------------------
  it("guard-the-guard: the layout source really was read", () => {
    const source = readFileSync(LAYOUT_PATH, "utf8");
    expect(source.length).toBeGreaterThan(500);
    expect(source).toContain("<html");
  });
});

describe("DS-14 (part 2) — the scaffold's assets are deleted, not left alongside the new icons", () => {
  for (const asset of SCAFFOLD_ASSETS) {
    it(`${asset} does not exist`, () => {
      expect(
        existsSync(resolve(REPO_ROOT, asset)),
        `${asset} is create-next-app residue and must stay deleted — with both it and a generated icon present, a browser is free to render either`,
      ).toBe(false);
    });
  }

  for (const [theme, path] of Object.entries(GENERATED_ICONS)) {
    it(`${path} exists and carries the ${theme} brand colour`, () => {
      // The colour check is what makes this more than a file-presence test. An icon regenerated
      // from a stale stylesheet, or hand-edited, or copied from its twin, still EXISTS — and a
      // suite that only counted files would call that a pass while the tab stopped tracking the
      // token contract. The expected hex is read from the generated module rather than pinned as a
      // literal, so a legitimate re-derivation of --brand moves both sides together and only a real
      // divergence between the two artifacts goes red.
      const file = resolve(REPO_ROOT, path);
      expect(existsSync(file), `${path} is missing — run \`npm run design:tokens\``).toBe(true);

      const svg = readFileSync(file, "utf8");
      const brand = THEME_TOKENS[theme as keyof typeof THEME_TOKENS]["--brand"].hex;
      expect(svg).toContain(brand);

      // No typeset glyph: an SVG favicon renders in an isolated document that loads no webfonts, so
      // the letterform is an outlined path (L9 / Pitfall 10).
      //
      // THE MARKUP IS ASSERTED, NOT THE FILE, and the difference is this phase's recurring
      // grep-versus-comment collision arriving for the fourteenth time — this time inside a test I
      // wrote rather than inside a plan criterion. The icon's own leading comment EXPLAINS that a
      // typeface attribute would silently not be honoured, so the file contains that string while
      // the drawing does not. The comment is stripped and the assertion made against what actually
      // renders, which is both the honest claim and the one that lets the artifact keep explaining
      // itself. The banned element is still named descriptively rather than spelled, because a
      // separate criterion greps the raw file for it.
      const markup = svg.replace(/<!--[\s\S]*?-->/g, "");
      expect(markup).toMatch(/<svg[\s>]/);
      expect(markup).not.toMatch(/<text[\s>]/);
      expect(markup).not.toContain("font-family");
    });
  }

  it("mounts FaviconSwap in the root layout", () => {
    // Import plus JSX — a bare import with no mount would satisfy a single occurrence, and an
    // unmounted swap component is indistinguishable from no themed favicon at all.
    const source = readFileSync(LAYOUT_PATH, "utf8");
    expect(source.split("FaviconSwap").length - 1).toBeGreaterThanOrEqual(2);
    expect(source).toMatch(/<FaviconSwap\s*\/>/);
  });

  it("leaves the icon link to exactly ONE owner — no metadata icons entry", () => {
    // THIS ENCODES A MEASUREMENT, not a preference, and it is the assertion most likely to be
    // "fixed" by someone who has not read the reasoning. An `icons:` entry in the metadata export
    // renders a <link> that React owns; FaviconSwap then re-points that element, React loses track
    // of its own node and re-creates it, and the page ships TWO icon links with the STALE one last.
    // Reproduced against a production build: grove ends up declaring both /icon-grove.svg and
    // /icon-court.svg, permanently. Which of two icon declarations a browser honours is not
    // specified, so that page's tab identity is decided by the user agent — the exact ambiguity
    // deleting favicon.ico was meant to remove.
    //
    // The check is deliberately structural rather than a bare string search: the layout's comment
    // EXPLAINS the absent entry at length, so it necessarily contains the word, and a criterion that
    // counted the word would be satisfied by the prose that argues against it.
    const source = readFileSync(LAYOUT_PATH, "utf8");
    const metadata = source.slice(source.indexOf("export const metadata"));
    const body = metadata.slice(0, metadata.indexOf("\n};"));
    expect(
      body,
      "layout.tsx declares metadata icons again — see src/components/theme/favicon-swap.tsx for the measurement",
    ).not.toMatch(/^\s*icons\s*:/m);

    // The hrefs live in the one owner, and both themes are reachable from it.
    const swap = readFileSync(FAVICON_SWAP_PATH, "utf8");
    expect(swap).toContain("/icon-court.svg");
    expect(swap).toContain("/icon-grove.svg");
    expect(swap).toContain('rel="icon"');
  });

  // -------------------------------------------------------------------------
  // Guard the guard (T-10-06): six of the assertions above are NEGATIVES over
  // `existsSync`, and every one of them passes trivially if REPO_ROOT is wrong.
  // A typo'd root reports the whole scaffold deleted AND would report the new
  // icons missing — but the icon assertions are the only positives here, so the
  // root is proven against a file this suite already depends on.
  // -------------------------------------------------------------------------
  it("guard-the-guard: the repository root really resolves", () => {
    expect(existsSync(resolve(REPO_ROOT, "package.json"))).toBe(true);
    expect(existsSync(resolve(REPO_ROOT, "src/app/layout.tsx"))).toBe(true);
    // A path shaped exactly like the deleted ones, under a directory that does exist.
    expect(existsSync(resolve(REPO_ROOT, "public"))).toBe(true);
  });
});
